/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#include "CellBarred.h"

static asn_per_constraints_t asn_PER_type_CellBarred_constr_1 = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_barred_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CellBarred__barred, intraFreqCellReselectionInd),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AllowedIndicator,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"intraFreqCellReselectionInd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CellBarred__barred, t_Barred),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_T_Barred,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"t-Barred"
		},
};
static ber_tlv_tag_t asn_DEF_barred_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_barred_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* intraFreqCellReselectionInd at 461 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* t-Barred at 463 */
};
static asn_SEQUENCE_specifics_t asn_SPC_barred_specs_2 = {
	sizeof(struct CellBarred__barred),
	offsetof(struct CellBarred__barred, _asn_ctx),
	asn_MAP_barred_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_barred_2 = {
	"barred",
	"barred",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_barred_tags_2,
	sizeof(asn_DEF_barred_tags_2)
		/sizeof(asn_DEF_barred_tags_2[0]) - 1, /* 1 */
	asn_DEF_barred_tags_2,	/* Same as above */
	sizeof(asn_DEF_barred_tags_2)
		/sizeof(asn_DEF_barred_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_barred_2,
	2,	/* Elements count */
	&asn_SPC_barred_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CellBarred_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CellBarred, choice.barred),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_barred_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"barred"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CellBarred, choice.notBarred),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"notBarred"
		},
};
static asn_TYPE_tag2member_t asn_MAP_CellBarred_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* barred at 461 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* notBarred at 464 */
};
static asn_CHOICE_specifics_t asn_SPC_CellBarred_specs_1 = {
	sizeof(struct CellBarred),
	offsetof(struct CellBarred, _asn_ctx),
	offsetof(struct CellBarred, present),
	sizeof(((struct CellBarred *)0)->present),
	asn_MAP_CellBarred_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CellBarred = {
	"CellBarred",
	"CellBarred",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_CellBarred_constr_1,
	asn_MBR_CellBarred_1,
	2,	/* Elements count */
	&asn_SPC_CellBarred_specs_1	/* Additional specs */
};

