/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Internode-definitions"
 * 	found in "../asn/Internode-definitions.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#include "CipheringStatusCNdomain-r4.h"

static asn_TYPE_member_t asn_MBR_CipheringStatusCNdomain_r4_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CipheringStatusCNdomain_r4, cn_DomainIdentity),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CN_DomainIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cn-DomainIdentity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CipheringStatusCNdomain_r4, cipheringStatus),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CipheringStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cipheringStatus"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CipheringStatusCNdomain_r4, start_Value),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_START_Value,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"start-Value"
		},
};
static ber_tlv_tag_t asn_DEF_CipheringStatusCNdomain_r4_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_CipheringStatusCNdomain_r4_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cn-DomainIdentity at 1509 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cipheringStatus at 1510 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* start-Value at 1512 */
};
static asn_SEQUENCE_specifics_t asn_SPC_CipheringStatusCNdomain_r4_specs_1 = {
	sizeof(struct CipheringStatusCNdomain_r4),
	offsetof(struct CipheringStatusCNdomain_r4, _asn_ctx),
	asn_MAP_CipheringStatusCNdomain_r4_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CipheringStatusCNdomain_r4 = {
	"CipheringStatusCNdomain-r4",
	"CipheringStatusCNdomain-r4",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CipheringStatusCNdomain_r4_tags_1,
	sizeof(asn_DEF_CipheringStatusCNdomain_r4_tags_1)
		/sizeof(asn_DEF_CipheringStatusCNdomain_r4_tags_1[0]), /* 1 */
	asn_DEF_CipheringStatusCNdomain_r4_tags_1,	/* Same as above */
	sizeof(asn_DEF_CipheringStatusCNdomain_r4_tags_1)
		/sizeof(asn_DEF_CipheringStatusCNdomain_r4_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CipheringStatusCNdomain_r4_1,
	3,	/* Elements count */
	&asn_SPC_CipheringStatusCNdomain_r4_specs_1	/* Additional specs */
};

