/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#include "DL-CommonTransChInfo-r4.h"

static asn_per_constraints_t asn_PER_type_dl_Parameters_constr_5 = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_modeSpecificInfo_constr_3 = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_dl_DCH_TFCS_6[] = {
	{ ATF_POINTER, 1, offsetof(struct DL_CommonTransChInfo_r4__modeSpecificInfo__fdd__dl_Parameters__dl_DCH_TFCS, tfcs),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TFCS,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"tfcs"
		},
};
static int asn_MAP_dl_DCH_TFCS_oms_6[] = { 0 };
static ber_tlv_tag_t asn_DEF_dl_DCH_TFCS_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_dl_DCH_TFCS_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* tfcs at 5151 */
};
static asn_SEQUENCE_specifics_t asn_SPC_dl_DCH_TFCS_specs_6 = {
	sizeof(struct DL_CommonTransChInfo_r4__modeSpecificInfo__fdd__dl_Parameters__dl_DCH_TFCS),
	offsetof(struct DL_CommonTransChInfo_r4__modeSpecificInfo__fdd__dl_Parameters__dl_DCH_TFCS, _asn_ctx),
	asn_MAP_dl_DCH_TFCS_tag2el_6,
	1,	/* Count of tags in the map */
	asn_MAP_dl_DCH_TFCS_oms_6,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_dl_DCH_TFCS_6 = {
	"dl-DCH-TFCS",
	"dl-DCH-TFCS",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_dl_DCH_TFCS_tags_6,
	sizeof(asn_DEF_dl_DCH_TFCS_tags_6)
		/sizeof(asn_DEF_dl_DCH_TFCS_tags_6[0]) - 1, /* 1 */
	asn_DEF_dl_DCH_TFCS_tags_6,	/* Same as above */
	sizeof(asn_DEF_dl_DCH_TFCS_tags_6)
		/sizeof(asn_DEF_dl_DCH_TFCS_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_dl_DCH_TFCS_6,
	1,	/* Elements count */
	&asn_SPC_dl_DCH_TFCS_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_dl_Parameters_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DL_CommonTransChInfo_r4__modeSpecificInfo__fdd__dl_Parameters, choice.dl_DCH_TFCS),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_dl_DCH_TFCS_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dl-DCH-TFCS"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DL_CommonTransChInfo_r4__modeSpecificInfo__fdd__dl_Parameters, choice.sameAsUL),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sameAsUL"
		},
};
static asn_TYPE_tag2member_t asn_MAP_dl_Parameters_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dl-DCH-TFCS at 5151 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* sameAsUL at 5153 */
};
static asn_CHOICE_specifics_t asn_SPC_dl_Parameters_specs_5 = {
	sizeof(struct DL_CommonTransChInfo_r4__modeSpecificInfo__fdd__dl_Parameters),
	offsetof(struct DL_CommonTransChInfo_r4__modeSpecificInfo__fdd__dl_Parameters, _asn_ctx),
	offsetof(struct DL_CommonTransChInfo_r4__modeSpecificInfo__fdd__dl_Parameters, present),
	sizeof(((struct DL_CommonTransChInfo_r4__modeSpecificInfo__fdd__dl_Parameters *)0)->present),
	asn_MAP_dl_Parameters_tag2el_5,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_dl_Parameters_5 = {
	"dl-Parameters",
	"dl-Parameters",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_dl_Parameters_constr_5,
	asn_MBR_dl_Parameters_5,
	2,	/* Elements count */
	&asn_SPC_dl_Parameters_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_fdd_4[] = {
	{ ATF_POINTER, 1, offsetof(struct DL_CommonTransChInfo_r4__modeSpecificInfo__fdd, dl_Parameters),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_dl_Parameters_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dl-Parameters"
		},
};
static int asn_MAP_fdd_oms_4[] = { 0 };
static ber_tlv_tag_t asn_DEF_fdd_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_fdd_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* dl-Parameters at 5152 */
};
static asn_SEQUENCE_specifics_t asn_SPC_fdd_specs_4 = {
	sizeof(struct DL_CommonTransChInfo_r4__modeSpecificInfo__fdd),
	offsetof(struct DL_CommonTransChInfo_r4__modeSpecificInfo__fdd, _asn_ctx),
	asn_MAP_fdd_tag2el_4,
	1,	/* Count of tags in the map */
	asn_MAP_fdd_oms_4,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_fdd_4 = {
	"fdd",
	"fdd",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_fdd_tags_4,
	sizeof(asn_DEF_fdd_tags_4)
		/sizeof(asn_DEF_fdd_tags_4[0]) - 1, /* 1 */
	asn_DEF_fdd_tags_4,	/* Same as above */
	sizeof(asn_DEF_fdd_tags_4)
		/sizeof(asn_DEF_fdd_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_fdd_4,
	1,	/* Elements count */
	&asn_SPC_fdd_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_tdd_9[] = {
	{ ATF_POINTER, 1, offsetof(struct DL_CommonTransChInfo_r4__modeSpecificInfo__tdd, individualDL_CCTrCH_InfoList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IndividualDL_CCTrCH_InfoList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"individualDL-CCTrCH-InfoList"
		},
};
static int asn_MAP_tdd_oms_9[] = { 0 };
static ber_tlv_tag_t asn_DEF_tdd_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_tdd_tag2el_9[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* individualDL-CCTrCH-InfoList at 5158 */
};
static asn_SEQUENCE_specifics_t asn_SPC_tdd_specs_9 = {
	sizeof(struct DL_CommonTransChInfo_r4__modeSpecificInfo__tdd),
	offsetof(struct DL_CommonTransChInfo_r4__modeSpecificInfo__tdd, _asn_ctx),
	asn_MAP_tdd_tag2el_9,
	1,	/* Count of tags in the map */
	asn_MAP_tdd_oms_9,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_tdd_9 = {
	"tdd",
	"tdd",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_tdd_tags_9,
	sizeof(asn_DEF_tdd_tags_9)
		/sizeof(asn_DEF_tdd_tags_9[0]) - 1, /* 1 */
	asn_DEF_tdd_tags_9,	/* Same as above */
	sizeof(asn_DEF_tdd_tags_9)
		/sizeof(asn_DEF_tdd_tags_9[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_tdd_9,
	1,	/* Elements count */
	&asn_SPC_tdd_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_modeSpecificInfo_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DL_CommonTransChInfo_r4__modeSpecificInfo, choice.fdd),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_fdd_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"fdd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DL_CommonTransChInfo_r4__modeSpecificInfo, choice.tdd),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_tdd_9,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"tdd"
		},
};
static asn_TYPE_tag2member_t asn_MAP_modeSpecificInfo_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fdd at 5154 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* tdd at 5158 */
};
static asn_CHOICE_specifics_t asn_SPC_modeSpecificInfo_specs_3 = {
	sizeof(struct DL_CommonTransChInfo_r4__modeSpecificInfo),
	offsetof(struct DL_CommonTransChInfo_r4__modeSpecificInfo, _asn_ctx),
	offsetof(struct DL_CommonTransChInfo_r4__modeSpecificInfo, present),
	sizeof(((struct DL_CommonTransChInfo_r4__modeSpecificInfo *)0)->present),
	asn_MAP_modeSpecificInfo_tag2el_3,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_modeSpecificInfo_3 = {
	"modeSpecificInfo",
	"modeSpecificInfo",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_modeSpecificInfo_constr_3,
	asn_MBR_modeSpecificInfo_3,
	2,	/* Elements count */
	&asn_SPC_modeSpecificInfo_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_DL_CommonTransChInfo_r4_1[] = {
	{ ATF_POINTER, 2, offsetof(struct DL_CommonTransChInfo_r4, sccpch_TFCS),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TFCS,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sccpch-TFCS"
		},
	{ ATF_POINTER, 1, offsetof(struct DL_CommonTransChInfo_r4, modeSpecificInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_modeSpecificInfo_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"modeSpecificInfo"
		},
};
static int asn_MAP_DL_CommonTransChInfo_r4_oms_1[] = { 0, 1 };
static ber_tlv_tag_t asn_DEF_DL_CommonTransChInfo_r4_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_DL_CommonTransChInfo_r4_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sccpch-TFCS at 5146 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* modeSpecificInfo at 5155 */
};
static asn_SEQUENCE_specifics_t asn_SPC_DL_CommonTransChInfo_r4_specs_1 = {
	sizeof(struct DL_CommonTransChInfo_r4),
	offsetof(struct DL_CommonTransChInfo_r4, _asn_ctx),
	asn_MAP_DL_CommonTransChInfo_r4_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_DL_CommonTransChInfo_r4_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DL_CommonTransChInfo_r4 = {
	"DL-CommonTransChInfo-r4",
	"DL-CommonTransChInfo-r4",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DL_CommonTransChInfo_r4_tags_1,
	sizeof(asn_DEF_DL_CommonTransChInfo_r4_tags_1)
		/sizeof(asn_DEF_DL_CommonTransChInfo_r4_tags_1[0]), /* 1 */
	asn_DEF_DL_CommonTransChInfo_r4_tags_1,	/* Same as above */
	sizeof(asn_DEF_DL_CommonTransChInfo_r4_tags_1)
		/sizeof(asn_DEF_DL_CommonTransChInfo_r4_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DL_CommonTransChInfo_r4_1,
	2,	/* Elements count */
	&asn_SPC_DL_CommonTransChInfo_r4_specs_1	/* Additional specs */
};

