/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "../asn/PDU-definitions.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#include "DownlinkDirectTransfer-r3-IEs.h"

static asn_TYPE_member_t asn_MBR_DownlinkDirectTransfer_r3_IEs_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DownlinkDirectTransfer_r3_IEs, rrc_TransactionIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRC_TransactionIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrc-TransactionIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DownlinkDirectTransfer_r3_IEs, cn_DomainIdentity),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CN_DomainIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cn-DomainIdentity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DownlinkDirectTransfer_r3_IEs, nas_Message),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NAS_Message,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nas-Message"
		},
};
static ber_tlv_tag_t asn_DEF_DownlinkDirectTransfer_r3_IEs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_DownlinkDirectTransfer_r3_IEs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrc-TransactionIdentifier at 2340 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cn-DomainIdentity at 2342 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* nas-Message at 2344 */
};
static asn_SEQUENCE_specifics_t asn_SPC_DownlinkDirectTransfer_r3_IEs_specs_1 = {
	sizeof(struct DownlinkDirectTransfer_r3_IEs),
	offsetof(struct DownlinkDirectTransfer_r3_IEs, _asn_ctx),
	asn_MAP_DownlinkDirectTransfer_r3_IEs_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DownlinkDirectTransfer_r3_IEs = {
	"DownlinkDirectTransfer-r3-IEs",
	"DownlinkDirectTransfer-r3-IEs",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DownlinkDirectTransfer_r3_IEs_tags_1,
	sizeof(asn_DEF_DownlinkDirectTransfer_r3_IEs_tags_1)
		/sizeof(asn_DEF_DownlinkDirectTransfer_r3_IEs_tags_1[0]), /* 1 */
	asn_DEF_DownlinkDirectTransfer_r3_IEs_tags_1,	/* Same as above */
	sizeof(asn_DEF_DownlinkDirectTransfer_r3_IEs_tags_1)
		/sizeof(asn_DEF_DownlinkDirectTransfer_r3_IEs_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DownlinkDirectTransfer_r3_IEs_1,
	3,	/* Elements count */
	&asn_SPC_DownlinkDirectTransfer_r3_IEs_specs_1	/* Additional specs */
};

