/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#include "ExtGANSS-SIBTypeInfoSchedulingInfo.h"

static int
memb_ganssID_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 7)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ganssScheduling_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 32)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_ganssScheduling_constr_4 = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 5,  5,  1,  32 }	/* (SIZE(1..32)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ganssID_constr_2 = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ganssScheduling_constr_4 = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 5,  5,  1,  32 }	/* (SIZE(1..32)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ganssScheduling_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ExtGANSS_SchedulingInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_ganssScheduling_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ganssScheduling_specs_4 = {
	sizeof(struct ExtGANSS_SIBTypeInfoSchedulingInfo__ganssScheduling),
	offsetof(struct ExtGANSS_SIBTypeInfoSchedulingInfo__ganssScheduling, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ganssScheduling_4 = {
	"ganssScheduling",
	"ganssScheduling",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ganssScheduling_tags_4,
	sizeof(asn_DEF_ganssScheduling_tags_4)
		/sizeof(asn_DEF_ganssScheduling_tags_4[0]) - 1, /* 1 */
	asn_DEF_ganssScheduling_tags_4,	/* Same as above */
	sizeof(asn_DEF_ganssScheduling_tags_4)
		/sizeof(asn_DEF_ganssScheduling_tags_4[0]), /* 2 */
	&asn_PER_type_ganssScheduling_constr_4,
	asn_MBR_ganssScheduling_4,
	1,	/* Single element */
	&asn_SPC_ganssScheduling_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ExtGANSS_SIBTypeInfoSchedulingInfo_1[] = {
	{ ATF_POINTER, 2, offsetof(struct ExtGANSS_SIBTypeInfoSchedulingInfo, ganssID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_ganssID_constraint_1,
		&asn_PER_memb_ganssID_constr_2,
		0,
		"ganssID"
		},
	{ ATF_POINTER, 1, offsetof(struct ExtGANSS_SIBTypeInfoSchedulingInfo, sbasID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_Positioning_GANSS_SBAS_ID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sbasID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ExtGANSS_SIBTypeInfoSchedulingInfo, ganssScheduling),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_ganssScheduling_4,
		memb_ganssScheduling_constraint_1,
		&asn_PER_memb_ganssScheduling_constr_4,
		0,
		"ganssScheduling"
		},
};
static int asn_MAP_ExtGANSS_SIBTypeInfoSchedulingInfo_oms_1[] = { 0, 1 };
static ber_tlv_tag_t asn_DEF_ExtGANSS_SIBTypeInfoSchedulingInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ExtGANSS_SIBTypeInfoSchedulingInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ganssID at 20169 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sbasID at 20170 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* ganssScheduling at 20173 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ExtGANSS_SIBTypeInfoSchedulingInfo_specs_1 = {
	sizeof(struct ExtGANSS_SIBTypeInfoSchedulingInfo),
	offsetof(struct ExtGANSS_SIBTypeInfoSchedulingInfo, _asn_ctx),
	asn_MAP_ExtGANSS_SIBTypeInfoSchedulingInfo_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_ExtGANSS_SIBTypeInfoSchedulingInfo_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ExtGANSS_SIBTypeInfoSchedulingInfo = {
	"ExtGANSS-SIBTypeInfoSchedulingInfo",
	"ExtGANSS-SIBTypeInfoSchedulingInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ExtGANSS_SIBTypeInfoSchedulingInfo_tags_1,
	sizeof(asn_DEF_ExtGANSS_SIBTypeInfoSchedulingInfo_tags_1)
		/sizeof(asn_DEF_ExtGANSS_SIBTypeInfoSchedulingInfo_tags_1[0]), /* 1 */
	asn_DEF_ExtGANSS_SIBTypeInfoSchedulingInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_ExtGANSS_SIBTypeInfoSchedulingInfo_tags_1)
		/sizeof(asn_DEF_ExtGANSS_SIBTypeInfoSchedulingInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ExtGANSS_SIBTypeInfoSchedulingInfo_1,
	3,	/* Elements count */
	&asn_SPC_ExtGANSS_SIBTypeInfoSchedulingInfo_specs_1	/* Additional specs */
};

