/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#include "HorizontalVelocity.h"

static int
memb_bearing_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 359)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_horizontalSpeed_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 2047)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_bearing_constr_2 = {
	{ APC_CONSTRAINED,	 9,  9,  0,  359 }	/* (0..359) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_horizontalSpeed_constr_3 = {
	{ APC_CONSTRAINED,	 11,  11,  0,  2047 }	/* (0..2047) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_HorizontalVelocity_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HorizontalVelocity, bearing),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_bearing_constraint_1,
		&asn_PER_memb_bearing_constr_2,
		0,
		"bearing"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HorizontalVelocity, horizontalSpeed),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_horizontalSpeed_constraint_1,
		&asn_PER_memb_horizontalSpeed_constr_3,
		0,
		"horizontalSpeed"
		},
};
static ber_tlv_tag_t asn_DEF_HorizontalVelocity_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_HorizontalVelocity_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* bearing at 14964 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* horizontalSpeed at 14965 */
};
static asn_SEQUENCE_specifics_t asn_SPC_HorizontalVelocity_specs_1 = {
	sizeof(struct HorizontalVelocity),
	offsetof(struct HorizontalVelocity, _asn_ctx),
	asn_MAP_HorizontalVelocity_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_HorizontalVelocity = {
	"HorizontalVelocity",
	"HorizontalVelocity",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_HorizontalVelocity_tags_1,
	sizeof(asn_DEF_HorizontalVelocity_tags_1)
		/sizeof(asn_DEF_HorizontalVelocity_tags_1[0]), /* 1 */
	asn_DEF_HorizontalVelocity_tags_1,	/* Same as above */
	sizeof(asn_DEF_HorizontalVelocity_tags_1)
		/sizeof(asn_DEF_HorizontalVelocity_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_HorizontalVelocity_1,
	2,	/* Elements count */
	&asn_SPC_HorizontalVelocity_specs_1	/* Additional specs */
};

