/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#include "HS-DSCH-SPS-Information-TDD128.h"

static asn_per_constraints_t asn_PER_type_hs_dsch_SPS_Operation_constr_2 = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_hs_dsch_SPS_Operation_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HS_DSCH_SPS_Information_TDD128__hs_dsch_SPS_Operation, choice.Continue),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"continue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HS_DSCH_SPS_Information_TDD128__hs_dsch_SPS_Operation, choice.newOperation),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HS_DSCH_SPS_NewOperation_TDD128,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"newOperation"
		},
};
static asn_TYPE_tag2member_t asn_MAP_hs_dsch_SPS_Operation_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* continue at 8879 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* newOperation at 8881 */
};
static asn_CHOICE_specifics_t asn_SPC_hs_dsch_SPS_Operation_specs_2 = {
	sizeof(struct HS_DSCH_SPS_Information_TDD128__hs_dsch_SPS_Operation),
	offsetof(struct HS_DSCH_SPS_Information_TDD128__hs_dsch_SPS_Operation, _asn_ctx),
	offsetof(struct HS_DSCH_SPS_Information_TDD128__hs_dsch_SPS_Operation, present),
	sizeof(((struct HS_DSCH_SPS_Information_TDD128__hs_dsch_SPS_Operation *)0)->present),
	asn_MAP_hs_dsch_SPS_Operation_tag2el_2,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_hs_dsch_SPS_Operation_2 = {
	"hs-dsch-SPS-Operation",
	"hs-dsch-SPS-Operation",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_hs_dsch_SPS_Operation_constr_2,
	asn_MBR_hs_dsch_SPS_Operation_2,
	2,	/* Elements count */
	&asn_SPC_hs_dsch_SPS_Operation_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_HS_DSCH_SPS_Information_TDD128_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HS_DSCH_SPS_Information_TDD128, hs_dsch_SPS_Operation),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_hs_dsch_SPS_Operation_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"hs-dsch-SPS-Operation"
		},
};
static ber_tlv_tag_t asn_DEF_HS_DSCH_SPS_Information_TDD128_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_HS_DSCH_SPS_Information_TDD128_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* hs-dsch-SPS-Operation at 8879 */
};
static asn_SEQUENCE_specifics_t asn_SPC_HS_DSCH_SPS_Information_TDD128_specs_1 = {
	sizeof(struct HS_DSCH_SPS_Information_TDD128),
	offsetof(struct HS_DSCH_SPS_Information_TDD128, _asn_ctx),
	asn_MAP_HS_DSCH_SPS_Information_TDD128_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_HS_DSCH_SPS_Information_TDD128 = {
	"HS-DSCH-SPS-Information-TDD128",
	"HS-DSCH-SPS-Information-TDD128",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_HS_DSCH_SPS_Information_TDD128_tags_1,
	sizeof(asn_DEF_HS_DSCH_SPS_Information_TDD128_tags_1)
		/sizeof(asn_DEF_HS_DSCH_SPS_Information_TDD128_tags_1[0]), /* 1 */
	asn_DEF_HS_DSCH_SPS_Information_TDD128_tags_1,	/* Same as above */
	sizeof(asn_DEF_HS_DSCH_SPS_Information_TDD128_tags_1)
		/sizeof(asn_DEF_HS_DSCH_SPS_Information_TDD128_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_HS_DSCH_SPS_Information_TDD128_1,
	1,	/* Elements count */
	&asn_SPC_HS_DSCH_SPS_Information_TDD128_specs_1	/* Additional specs */
};

