/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#include "IdentificationOfReceivedMessage.h"

static asn_TYPE_member_t asn_MBR_IdentificationOfReceivedMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IdentificationOfReceivedMessage, rrc_TransactionIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRC_TransactionIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrc-TransactionIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IdentificationOfReceivedMessage, receivedMessageType),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReceivedMessageType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"receivedMessageType"
		},
};
static ber_tlv_tag_t asn_DEF_IdentificationOfReceivedMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_IdentificationOfReceivedMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrc-TransactionIdentifier at 20268 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* receivedMessageType at 20270 */
};
static asn_SEQUENCE_specifics_t asn_SPC_IdentificationOfReceivedMessage_specs_1 = {
	sizeof(struct IdentificationOfReceivedMessage),
	offsetof(struct IdentificationOfReceivedMessage, _asn_ctx),
	asn_MAP_IdentificationOfReceivedMessage_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_IdentificationOfReceivedMessage = {
	"IdentificationOfReceivedMessage",
	"IdentificationOfReceivedMessage",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_IdentificationOfReceivedMessage_tags_1,
	sizeof(asn_DEF_IdentificationOfReceivedMessage_tags_1)
		/sizeof(asn_DEF_IdentificationOfReceivedMessage_tags_1[0]), /* 1 */
	asn_DEF_IdentificationOfReceivedMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_IdentificationOfReceivedMessage_tags_1)
		/sizeof(asn_DEF_IdentificationOfReceivedMessage_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_IdentificationOfReceivedMessage_1,
	2,	/* Elements count */
	&asn_SPC_IdentificationOfReceivedMessage_specs_1	/* Additional specs */
};

