/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "../asn/PDU-definitions.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#include "MBMSCommonPTMRBInformation.h"

static ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_12 = {
	sizeof(struct MBMSCommonPTMRBInformation__v770NonCriticalExtensions__v780NonCriticalExtensions__v860NonCriticalExtensions__nonCriticalExtensions),
	offsetof(struct MBMSCommonPTMRBInformation__v770NonCriticalExtensions__v780NonCriticalExtensions__v860NonCriticalExtensions__nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_12 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonCriticalExtensions_tags_12,
	sizeof(asn_DEF_nonCriticalExtensions_tags_12)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_12[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_12,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_12)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_12[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v860NonCriticalExtensions_10[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MBMSCommonPTMRBInformation__v770NonCriticalExtensions__v780NonCriticalExtensions__v860NonCriticalExtensions, mbmsCommonPTMRBInformation_v860ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMSCommonPTMRBInformation_v860ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mbmsCommonPTMRBInformation-v860ext"
		},
	{ ATF_POINTER, 1, offsetof(struct MBMSCommonPTMRBInformation__v770NonCriticalExtensions__v780NonCriticalExtensions__v860NonCriticalExtensions, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonCriticalExtensions"
		},
};
static int asn_MAP_v860NonCriticalExtensions_oms_10[] = { 1 };
static ber_tlv_tag_t asn_DEF_v860NonCriticalExtensions_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_v860NonCriticalExtensions_tag2el_10[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mbmsCommonPTMRBInformation-v860ext at 11211 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions at 11212 */
};
static asn_SEQUENCE_specifics_t asn_SPC_v860NonCriticalExtensions_specs_10 = {
	sizeof(struct MBMSCommonPTMRBInformation__v770NonCriticalExtensions__v780NonCriticalExtensions__v860NonCriticalExtensions),
	offsetof(struct MBMSCommonPTMRBInformation__v770NonCriticalExtensions__v780NonCriticalExtensions__v860NonCriticalExtensions, _asn_ctx),
	asn_MAP_v860NonCriticalExtensions_tag2el_10,
	2,	/* Count of tags in the map */
	asn_MAP_v860NonCriticalExtensions_oms_10,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v860NonCriticalExtensions_10 = {
	"v860NonCriticalExtensions",
	"v860NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v860NonCriticalExtensions_tags_10,
	sizeof(asn_DEF_v860NonCriticalExtensions_tags_10)
		/sizeof(asn_DEF_v860NonCriticalExtensions_tags_10[0]) - 1, /* 1 */
	asn_DEF_v860NonCriticalExtensions_tags_10,	/* Same as above */
	sizeof(asn_DEF_v860NonCriticalExtensions_tags_10)
		/sizeof(asn_DEF_v860NonCriticalExtensions_tags_10[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v860NonCriticalExtensions_10,
	2,	/* Elements count */
	&asn_SPC_v860NonCriticalExtensions_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v780NonCriticalExtensions_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MBMSCommonPTMRBInformation__v770NonCriticalExtensions__v780NonCriticalExtensions, mbmsCommonPTMRBInformation_v780ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMSCommonPTMRBInformation_v780ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mbmsCommonPTMRBInformation-v780ext"
		},
	{ ATF_POINTER, 1, offsetof(struct MBMSCommonPTMRBInformation__v770NonCriticalExtensions__v780NonCriticalExtensions, v860NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v860NonCriticalExtensions_10,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v860NonCriticalExtensions"
		},
};
static int asn_MAP_v780NonCriticalExtensions_oms_8[] = { 1 };
static ber_tlv_tag_t asn_DEF_v780NonCriticalExtensions_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_v780NonCriticalExtensions_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mbmsCommonPTMRBInformation-v780ext at 11208 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v860NonCriticalExtensions at 11211 */
};
static asn_SEQUENCE_specifics_t asn_SPC_v780NonCriticalExtensions_specs_8 = {
	sizeof(struct MBMSCommonPTMRBInformation__v770NonCriticalExtensions__v780NonCriticalExtensions),
	offsetof(struct MBMSCommonPTMRBInformation__v770NonCriticalExtensions__v780NonCriticalExtensions, _asn_ctx),
	asn_MAP_v780NonCriticalExtensions_tag2el_8,
	2,	/* Count of tags in the map */
	asn_MAP_v780NonCriticalExtensions_oms_8,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v780NonCriticalExtensions_8 = {
	"v780NonCriticalExtensions",
	"v780NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v780NonCriticalExtensions_tags_8,
	sizeof(asn_DEF_v780NonCriticalExtensions_tags_8)
		/sizeof(asn_DEF_v780NonCriticalExtensions_tags_8[0]) - 1, /* 1 */
	asn_DEF_v780NonCriticalExtensions_tags_8,	/* Same as above */
	sizeof(asn_DEF_v780NonCriticalExtensions_tags_8)
		/sizeof(asn_DEF_v780NonCriticalExtensions_tags_8[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v780NonCriticalExtensions_8,
	2,	/* Elements count */
	&asn_SPC_v780NonCriticalExtensions_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v770NonCriticalExtensions_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MBMSCommonPTMRBInformation__v770NonCriticalExtensions, mbmsCommonPTMRBInformation_v770ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMSCommonPTMRBInformation_v770ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mbmsCommonPTMRBInformation-v770ext"
		},
	{ ATF_POINTER, 1, offsetof(struct MBMSCommonPTMRBInformation__v770NonCriticalExtensions, v780NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v780NonCriticalExtensions_8,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v780NonCriticalExtensions"
		},
};
static int asn_MAP_v770NonCriticalExtensions_oms_6[] = { 1 };
static ber_tlv_tag_t asn_DEF_v770NonCriticalExtensions_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_v770NonCriticalExtensions_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mbmsCommonPTMRBInformation-v770ext at 11205 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v780NonCriticalExtensions at 11208 */
};
static asn_SEQUENCE_specifics_t asn_SPC_v770NonCriticalExtensions_specs_6 = {
	sizeof(struct MBMSCommonPTMRBInformation__v770NonCriticalExtensions),
	offsetof(struct MBMSCommonPTMRBInformation__v770NonCriticalExtensions, _asn_ctx),
	asn_MAP_v770NonCriticalExtensions_tag2el_6,
	2,	/* Count of tags in the map */
	asn_MAP_v770NonCriticalExtensions_oms_6,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v770NonCriticalExtensions_6 = {
	"v770NonCriticalExtensions",
	"v770NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v770NonCriticalExtensions_tags_6,
	sizeof(asn_DEF_v770NonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_v770NonCriticalExtensions_tags_6[0]) - 1, /* 1 */
	asn_DEF_v770NonCriticalExtensions_tags_6,	/* Same as above */
	sizeof(asn_DEF_v770NonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_v770NonCriticalExtensions_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v770NonCriticalExtensions_6,
	2,	/* Elements count */
	&asn_SPC_v770NonCriticalExtensions_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_MBMSCommonPTMRBInformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MBMSCommonPTMRBInformation, mbms_CommonRBInformationList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMS_CommonRBInformationList_r6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mbms-CommonRBInformationList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MBMSCommonPTMRBInformation, mbms_TranspChInfoForEachTrCh),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMS_TranspChInfoForEachTrCh_r6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mbms-TranspChInfoForEachTrCh"
		},
	{ ATF_POINTER, 1, offsetof(struct MBMSCommonPTMRBInformation, mbms_TranspChInfoForEachCCTrCh),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMS_TranspChInfoForEachCCTrCh_r6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mbms-TranspChInfoForEachCCTrCh"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MBMSCommonPTMRBInformation, mbms_PhyChInformationList),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMS_PhyChInformationList_r6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mbms-PhyChInformationList"
		},
	{ ATF_POINTER, 1, offsetof(struct MBMSCommonPTMRBInformation, v770NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_v770NonCriticalExtensions_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v770NonCriticalExtensions"
		},
};
static int asn_MAP_MBMSCommonPTMRBInformation_oms_1[] = { 2, 4 };
static ber_tlv_tag_t asn_DEF_MBMSCommonPTMRBInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_MBMSCommonPTMRBInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mbms-CommonRBInformationList at 11196 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* mbms-TranspChInfoForEachTrCh at 11197 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* mbms-TranspChInfoForEachCCTrCh at 11198 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* mbms-PhyChInformationList at 11201 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* v770NonCriticalExtensions at 11205 */
};
static asn_SEQUENCE_specifics_t asn_SPC_MBMSCommonPTMRBInformation_specs_1 = {
	sizeof(struct MBMSCommonPTMRBInformation),
	offsetof(struct MBMSCommonPTMRBInformation, _asn_ctx),
	asn_MAP_MBMSCommonPTMRBInformation_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_MBMSCommonPTMRBInformation_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_MBMSCommonPTMRBInformation = {
	"MBMSCommonPTMRBInformation",
	"MBMSCommonPTMRBInformation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MBMSCommonPTMRBInformation_tags_1,
	sizeof(asn_DEF_MBMSCommonPTMRBInformation_tags_1)
		/sizeof(asn_DEF_MBMSCommonPTMRBInformation_tags_1[0]), /* 1 */
	asn_DEF_MBMSCommonPTMRBInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_MBMSCommonPTMRBInformation_tags_1)
		/sizeof(asn_DEF_MBMSCommonPTMRBInformation_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_MBMSCommonPTMRBInformation_1,
	5,	/* Elements count */
	&asn_SPC_MBMSCommonPTMRBInformation_specs_1	/* Additional specs */
};

