/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#include "SecondaryCCPCHInfoDiff-MBMS.h"

static asn_TYPE_member_t asn_MBR_SecondaryCCPCHInfoDiff_MBMS_1[] = {
	{ ATF_POINTER, 1, offsetof(struct SecondaryCCPCHInfoDiff_MBMS, secondaryScramblingCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SecondaryScramblingCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"secondaryScramblingCode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SecondaryCCPCHInfoDiff_MBMS, sttd_Indicator),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sttd-Indicator"
		},
	{ ATF_POINTER, 2, offsetof(struct SecondaryCCPCHInfoDiff_MBMS, sf_AndCodeNumber),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SF256_AndCodeNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sf-AndCodeNumber"
		},
	{ ATF_POINTER, 1, offsetof(struct SecondaryCCPCHInfoDiff_MBMS, timingOffset),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimingOffset,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"timingOffset"
		},
};
static int asn_MAP_SecondaryCCPCHInfoDiff_MBMS_oms_1[] = { 0, 2, 3 };
static ber_tlv_tag_t asn_DEF_SecondaryCCPCHInfoDiff_MBMS_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SecondaryCCPCHInfoDiff_MBMS_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* secondaryScramblingCode at 11177 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sttd-Indicator at 11178 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sf-AndCodeNumber at 11179 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* timingOffset at 11180 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SecondaryCCPCHInfoDiff_MBMS_specs_1 = {
	sizeof(struct SecondaryCCPCHInfoDiff_MBMS),
	offsetof(struct SecondaryCCPCHInfoDiff_MBMS, _asn_ctx),
	asn_MAP_SecondaryCCPCHInfoDiff_MBMS_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_SecondaryCCPCHInfoDiff_MBMS_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SecondaryCCPCHInfoDiff_MBMS = {
	"SecondaryCCPCHInfoDiff-MBMS",
	"SecondaryCCPCHInfoDiff-MBMS",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SecondaryCCPCHInfoDiff_MBMS_tags_1,
	sizeof(asn_DEF_SecondaryCCPCHInfoDiff_MBMS_tags_1)
		/sizeof(asn_DEF_SecondaryCCPCHInfoDiff_MBMS_tags_1[0]), /* 1 */
	asn_DEF_SecondaryCCPCHInfoDiff_MBMS_tags_1,	/* Same as above */
	sizeof(asn_DEF_SecondaryCCPCHInfoDiff_MBMS_tags_1)
		/sizeof(asn_DEF_SecondaryCCPCHInfoDiff_MBMS_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SecondaryCCPCHInfoDiff_MBMS_1,
	4,	/* Elements count */
	&asn_SPC_SecondaryCCPCHInfoDiff_MBMS_specs_1	/* Additional specs */
};

