/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#include "UE-Positioning-OTDOA-AssistanceData.h"

static asn_TYPE_member_t asn_MBR_UE_Positioning_OTDOA_AssistanceData_1[] = {
	{ ATF_POINTER, 2, offsetof(struct UE_Positioning_OTDOA_AssistanceData, ue_positioning_OTDOA_ReferenceCellInfo),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_Positioning_OTDOA_ReferenceCellInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ue-positioning-OTDOA-ReferenceCellInfo"
		},
	{ ATF_POINTER, 1, offsetof(struct UE_Positioning_OTDOA_AssistanceData, ue_positioning_OTDOA_NeighbourCellList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_Positioning_OTDOA_NeighbourCellList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ue-positioning-OTDOA-NeighbourCellList"
		},
};
static int asn_MAP_UE_Positioning_OTDOA_AssistanceData_oms_1[] = { 0, 1 };
static ber_tlv_tag_t asn_DEF_UE_Positioning_OTDOA_AssistanceData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_UE_Positioning_OTDOA_AssistanceData_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ue-positioning-OTDOA-ReferenceCellInfo at 19487 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ue-positioning-OTDOA-NeighbourCellList at 19489 */
};
static asn_SEQUENCE_specifics_t asn_SPC_UE_Positioning_OTDOA_AssistanceData_specs_1 = {
	sizeof(struct UE_Positioning_OTDOA_AssistanceData),
	offsetof(struct UE_Positioning_OTDOA_AssistanceData, _asn_ctx),
	asn_MAP_UE_Positioning_OTDOA_AssistanceData_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_UE_Positioning_OTDOA_AssistanceData_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_UE_Positioning_OTDOA_AssistanceData = {
	"UE-Positioning-OTDOA-AssistanceData",
	"UE-Positioning-OTDOA-AssistanceData",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_UE_Positioning_OTDOA_AssistanceData_tags_1,
	sizeof(asn_DEF_UE_Positioning_OTDOA_AssistanceData_tags_1)
		/sizeof(asn_DEF_UE_Positioning_OTDOA_AssistanceData_tags_1[0]), /* 1 */
	asn_DEF_UE_Positioning_OTDOA_AssistanceData_tags_1,	/* Same as above */
	sizeof(asn_DEF_UE_Positioning_OTDOA_AssistanceData_tags_1)
		/sizeof(asn_DEF_UE_Positioning_OTDOA_AssistanceData_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_UE_Positioning_OTDOA_AssistanceData_1,
	2,	/* Elements count */
	&asn_SPC_UE_Positioning_OTDOA_AssistanceData_specs_1	/* Additional specs */
};

