/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#include "UE-RadioAccessCapabilityInfo-v770ext.h"

static int
ganssSupportIndication_4_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
ganssSupportIndication_4_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
ganssSupportIndication_4_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	ganssSupportIndication_4_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
ganssSupportIndication_4_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	ganssSupportIndication_4_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
ganssSupportIndication_4_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	ganssSupportIndication_4_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
ganssSupportIndication_4_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	ganssSupportIndication_4_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
ganssSupportIndication_4_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	ganssSupportIndication_4_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
ganssSupportIndication_4_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	ganssSupportIndication_4_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
ganssSupportIndication_4_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	ganssSupportIndication_4_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
ganssSupportIndication_4_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	ganssSupportIndication_4_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
mac_ehsSupport_6_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
mac_ehsSupport_6_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
mac_ehsSupport_6_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	mac_ehsSupport_6_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
mac_ehsSupport_6_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	mac_ehsSupport_6_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
mac_ehsSupport_6_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	mac_ehsSupport_6_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
mac_ehsSupport_6_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	mac_ehsSupport_6_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
mac_ehsSupport_6_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	mac_ehsSupport_6_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
mac_ehsSupport_6_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	mac_ehsSupport_6_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
mac_ehsSupport_6_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	mac_ehsSupport_6_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
mac_ehsSupport_6_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	mac_ehsSupport_6_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_per_constraints_t asn_PER_type_ganssSupportIndication_constr_4 = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_mac_ehsSupport_constr_6 = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_INTEGER_enum_map_t asn_MAP_ganssSupportIndication_value2enum_4[] = {
	{ 0,	4,	"true" }
};
static unsigned int asn_MAP_ganssSupportIndication_enum2value_4[] = {
	0	/* true(0) */
};
static asn_INTEGER_specifics_t asn_SPC_ganssSupportIndication_specs_4 = {
	asn_MAP_ganssSupportIndication_value2enum_4,	/* "tag" => N; sorted by tag */
	asn_MAP_ganssSupportIndication_enum2value_4,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_ganssSupportIndication_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ganssSupportIndication_4 = {
	"ganssSupportIndication",
	"ganssSupportIndication",
	ganssSupportIndication_4_free,
	ganssSupportIndication_4_print,
	ganssSupportIndication_4_constraint,
	ganssSupportIndication_4_decode_ber,
	ganssSupportIndication_4_encode_der,
	ganssSupportIndication_4_decode_xer,
	ganssSupportIndication_4_encode_xer,
	ganssSupportIndication_4_decode_uper,
	ganssSupportIndication_4_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ganssSupportIndication_tags_4,
	sizeof(asn_DEF_ganssSupportIndication_tags_4)
		/sizeof(asn_DEF_ganssSupportIndication_tags_4[0]) - 1, /* 1 */
	asn_DEF_ganssSupportIndication_tags_4,	/* Same as above */
	sizeof(asn_DEF_ganssSupportIndication_tags_4)
		/sizeof(asn_DEF_ganssSupportIndication_tags_4[0]), /* 2 */
	&asn_PER_type_ganssSupportIndication_constr_4,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ganssSupportIndication_specs_4	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_mac_ehsSupport_value2enum_6[] = {
	{ 0,	4,	"true" }
};
static unsigned int asn_MAP_mac_ehsSupport_enum2value_6[] = {
	0	/* true(0) */
};
static asn_INTEGER_specifics_t asn_SPC_mac_ehsSupport_specs_6 = {
	asn_MAP_mac_ehsSupport_value2enum_6,	/* "tag" => N; sorted by tag */
	asn_MAP_mac_ehsSupport_enum2value_6,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_mac_ehsSupport_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mac_ehsSupport_6 = {
	"mac-ehsSupport",
	"mac-ehsSupport",
	mac_ehsSupport_6_free,
	mac_ehsSupport_6_print,
	mac_ehsSupport_6_constraint,
	mac_ehsSupport_6_decode_ber,
	mac_ehsSupport_6_encode_der,
	mac_ehsSupport_6_decode_xer,
	mac_ehsSupport_6_encode_xer,
	mac_ehsSupport_6_decode_uper,
	mac_ehsSupport_6_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_mac_ehsSupport_tags_6,
	sizeof(asn_DEF_mac_ehsSupport_tags_6)
		/sizeof(asn_DEF_mac_ehsSupport_tags_6[0]) - 1, /* 1 */
	asn_DEF_mac_ehsSupport_tags_6,	/* Same as above */
	sizeof(asn_DEF_mac_ehsSupport_tags_6)
		/sizeof(asn_DEF_mac_ehsSupport_tags_6[0]), /* 2 */
	&asn_PER_type_mac_ehsSupport_constr_6,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_mac_ehsSupport_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_UE_RadioAccessCapabilityInfo_v770ext_1[] = {
	{ ATF_POINTER, 1, offsetof(struct UE_RadioAccessCapabilityInfo_v770ext, rf_Capability),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RF_Capability_v770ext,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rf-Capability"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UE_RadioAccessCapabilityInfo_v770ext, physicalChannelCapability),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysicalChannelCapabilityInfo_v770ext,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"physicalChannelCapability"
		},
	{ ATF_POINTER, 3, offsetof(struct UE_RadioAccessCapabilityInfo_v770ext, ganssSupportIndication),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ganssSupportIndication_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssSupportIndication"
		},
	{ ATF_POINTER, 2, offsetof(struct UE_RadioAccessCapabilityInfo_v770ext, mac_ehsSupport),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_mac_ehsSupport_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mac-ehsSupport"
		},
	{ ATF_POINTER, 1, offsetof(struct UE_RadioAccessCapabilityInfo_v770ext, ue_SpecificCapabilityInformation),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_SpecificCapabilityInformation_LCRTDD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ue-SpecificCapabilityInformation"
		},
};
static int asn_MAP_UE_RadioAccessCapabilityInfo_v770ext_oms_1[] = { 0, 2, 3, 4 };
static ber_tlv_tag_t asn_DEF_UE_RadioAccessCapabilityInfo_v770ext_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_UE_RadioAccessCapabilityInfo_v770ext_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rf-Capability at 2882 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* physicalChannelCapability at 2883 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ganssSupportIndication at 2884 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* mac-ehsSupport at 2885 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* ue-SpecificCapabilityInformation at 2886 */
};
static asn_SEQUENCE_specifics_t asn_SPC_UE_RadioAccessCapabilityInfo_v770ext_specs_1 = {
	sizeof(struct UE_RadioAccessCapabilityInfo_v770ext),
	offsetof(struct UE_RadioAccessCapabilityInfo_v770ext, _asn_ctx),
	asn_MAP_UE_RadioAccessCapabilityInfo_v770ext_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_UE_RadioAccessCapabilityInfo_v770ext_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_UE_RadioAccessCapabilityInfo_v770ext = {
	"UE-RadioAccessCapabilityInfo-v770ext",
	"UE-RadioAccessCapabilityInfo-v770ext",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_UE_RadioAccessCapabilityInfo_v770ext_tags_1,
	sizeof(asn_DEF_UE_RadioAccessCapabilityInfo_v770ext_tags_1)
		/sizeof(asn_DEF_UE_RadioAccessCapabilityInfo_v770ext_tags_1[0]), /* 1 */
	asn_DEF_UE_RadioAccessCapabilityInfo_v770ext_tags_1,	/* Same as above */
	sizeof(asn_DEF_UE_RadioAccessCapabilityInfo_v770ext_tags_1)
		/sizeof(asn_DEF_UE_RadioAccessCapabilityInfo_v770ext_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_UE_RadioAccessCapabilityInfo_v770ext_1,
	5,	/* Elements count */
	&asn_SPC_UE_RadioAccessCapabilityInfo_v770ext_specs_1	/* Additional specs */
};

