/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_Antenna3And4_D_CPICH_H_
#define	_Antenna3And4_D_CPICH_H_


#include <asn_application.h>

/* Including external dependencies */
#include "D-CPICH-PowerOffset-4x4MIMO.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Antenna3And4_D_CPICH__initialD_CPICHStatus {
	Antenna3And4_D_CPICH__initialD_CPICHStatus_activated	= 0
} e_Antenna3And4_D_CPICH__initialD_CPICHStatus;

/* Forward declarations */
struct Antenna3_D_CPICH;
struct Antenna4_D_CPICH;

/* Antenna3And4-D-CPICH */
typedef struct Antenna3And4_D_CPICH {
	struct Antenna3_D_CPICH	*antenna3_D_CPICH	/* OPTIONAL */;
	struct Antenna4_D_CPICH	*antenna4_D_CPICH	/* OPTIONAL */;
	D_CPICH_PowerOffset_4x4MIMO_t	*d_cpich_PowerOffset_Mimo	/* OPTIONAL */;
	long	*initialD_CPICHStatus	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Antenna3And4_D_CPICH_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_initialD_CPICHStatus_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Antenna3And4_D_CPICH;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Antenna3-D-CPICH.h"
#include "Antenna4-D-CPICH.h"

#endif	/* _Antenna3And4_D_CPICH_H_ */
#include <asn_internal.h>
