/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_CapabilityUpdateRequirement_r5_H_
#define	_CapabilityUpdateRequirement_r5_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SystemSpecificCapUpdateReqList_r5;

/* CapabilityUpdateRequirement-r5 */
typedef struct CapabilityUpdateRequirement_r5 {
	BOOLEAN_t	 ue_RadioCapabilityFDDUpdateRequirement_FDD;
	BOOLEAN_t	 ue_RadioCapabilityTDDUpdateRequirement_TDD384;
	BOOLEAN_t	 ue_RadioCapabilityTDDUpdateRequirement_TDD128;
	struct SystemSpecificCapUpdateReqList_r5	*systemSpecificCapUpdateReqList	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CapabilityUpdateRequirement_r5_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CapabilityUpdateRequirement_r5;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SystemSpecificCapUpdateReqList-r5.h"

#endif	/* _CapabilityUpdateRequirement_r5_H_ */
#include <asn_internal.h>
