/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Internode-definitions"
 * 	found in "../asn/Internode-definitions.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_CipheringStatus_H_
#define	_CipheringStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CipheringStatus {
	CipheringStatus_started	= 0,
	CipheringStatus_notStarted	= 1
} e_CipheringStatus;

/* CipheringStatus */
typedef long	 CipheringStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CipheringStatus;
asn_struct_free_f CipheringStatus_free;
asn_struct_print_f CipheringStatus_print;
asn_constr_check_f CipheringStatus_constraint;
ber_type_decoder_f CipheringStatus_decode_ber;
der_type_encoder_f CipheringStatus_encode_der;
xer_type_decoder_f CipheringStatus_decode_xer;
xer_type_encoder_f CipheringStatus_encode_xer;
per_type_decoder_f CipheringStatus_decode_uper;
per_type_encoder_f CipheringStatus_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CipheringStatus_H_ */
#include <asn_internal.h>
