/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_CommonDynamicTF_InfoList_DynamicTTI_H_
#define	_CommonDynamicTF_InfoList_DynamicTTI_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CommonDynamicTF_Info_DynamicTTI;

/* CommonDynamicTF-InfoList-DynamicTTI */
typedef struct CommonDynamicTF_InfoList_DynamicTTI {
	A_SEQUENCE_OF(struct CommonDynamicTF_Info_DynamicTTI) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CommonDynamicTF_InfoList_DynamicTTI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CommonDynamicTF_InfoList_DynamicTTI;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CommonDynamicTF-Info-DynamicTTI.h"

#endif	/* _CommonDynamicTF_InfoList_DynamicTTI_H_ */
#include <asn_internal.h>
