/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_DL_PhysChCapabilityFDD_v770ext_H_
#define	_DL_PhysChCapabilityFDD_v770ext_H_


#include <asn_application.h>

/* Including external dependencies */
#include "HSDSCH-physical-layer-category-ext.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DL_PhysChCapabilityFDD_v770ext__hsscchlessHsdschOperation {
	DL_PhysChCapabilityFDD_v770ext__hsscchlessHsdschOperation_true	= 0
} e_DL_PhysChCapabilityFDD_v770ext__hsscchlessHsdschOperation;
typedef enum DL_PhysChCapabilityFDD_v770ext__enhancedFdpch {
	DL_PhysChCapabilityFDD_v770ext__enhancedFdpch_true	= 0
} e_DL_PhysChCapabilityFDD_v770ext__enhancedFdpch;
typedef enum DL_PhysChCapabilityFDD_v770ext__hsdschReception_CellFach {
	DL_PhysChCapabilityFDD_v770ext__hsdschReception_CellFach_true	= 0
} e_DL_PhysChCapabilityFDD_v770ext__hsdschReception_CellFach;
typedef enum DL_PhysChCapabilityFDD_v770ext__hsdschReception_CellUraPch {
	DL_PhysChCapabilityFDD_v770ext__hsdschReception_CellUraPch_true	= 0
} e_DL_PhysChCapabilityFDD_v770ext__hsdschReception_CellUraPch;

/* DL-PhysChCapabilityFDD-v770ext */
typedef struct DL_PhysChCapabilityFDD_v770ext {
	HSDSCH_physical_layer_category_ext_t	*hsdsch_physical_layer_category_ext	/* OPTIONAL */;
	long	*hsscchlessHsdschOperation	/* OPTIONAL */;
	long	*enhancedFdpch	/* OPTIONAL */;
	long	*hsdschReception_CellFach	/* OPTIONAL */;
	long	*hsdschReception_CellUraPch	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DL_PhysChCapabilityFDD_v770ext_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_hsscchlessHsdschOperation_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_enhancedFdpch_5;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_hsdschReception_CellFach_7;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_hsdschReception_CellUraPch_9;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_DL_PhysChCapabilityFDD_v770ext;

#ifdef __cplusplus
}
#endif

#endif	/* _DL_PhysChCapabilityFDD_v770ext_H_ */
#include <asn_internal.h>
