/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_DomainSpecificAccessRestrictionForSharedNetwork_v670ext_H_
#define	_DomainSpecificAccessRestrictionForSharedNetwork_v670ext_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DomainSpecificAccessRestrictionList-v670ext.h"
#include "DomainSpecificAccessRestrictionParam-v670ext.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DomainSpecificAccessRestrictionForSharedNetwork_v670ext_PR {
	DomainSpecificAccessRestrictionForSharedNetwork_v670ext_PR_NOTHING,	/* No components present */
	DomainSpecificAccessRestrictionForSharedNetwork_v670ext_PR_domainSpecificAccessRestictionList,
	DomainSpecificAccessRestrictionForSharedNetwork_v670ext_PR_domainSpecificAccessRestictionParametersForAll
} DomainSpecificAccessRestrictionForSharedNetwork_v670ext_PR;

/* DomainSpecificAccessRestrictionForSharedNetwork-v670ext */
typedef struct DomainSpecificAccessRestrictionForSharedNetwork_v670ext {
	DomainSpecificAccessRestrictionForSharedNetwork_v670ext_PR present;
	union DomainSpecificAccessRestrictionForSharedNetwork_v670ext_u {
		DomainSpecificAccessRestrictionList_v670ext_t	 domainSpecificAccessRestictionList;
		DomainSpecificAccessRestrictionParam_v670ext_t	 domainSpecificAccessRestictionParametersForAll;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DomainSpecificAccessRestrictionForSharedNetwork_v670ext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DomainSpecificAccessRestrictionForSharedNetwork_v670ext;

#ifdef __cplusplus
}
#endif

#endif	/* _DomainSpecificAccessRestrictionForSharedNetwork_v670ext_H_ */
#include <asn_internal.h>
