/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_E_DCH_AddReconf_MAC_d_FlowList_H_
#define	_E_DCH_AddReconf_MAC_d_FlowList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct E_DCH_AddReconf_MAC_d_Flow;

/* E-DCH-AddReconf-MAC-d-FlowList */
typedef struct E_DCH_AddReconf_MAC_d_FlowList {
	A_SEQUENCE_OF(struct E_DCH_AddReconf_MAC_d_Flow) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E_DCH_AddReconf_MAC_d_FlowList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E_DCH_AddReconf_MAC_d_FlowList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "E-DCH-AddReconf-MAC-d-Flow.h"

#endif	/* _E_DCH_AddReconf_MAC_d_FlowList_H_ */
#include <asn_internal.h>
