/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "../asn/PDU-definitions.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_HandoverFromUTRANCommand_GSM_v690ext_IEs_H_
#define	_HandoverFromUTRANCommand_GSM_v690ext_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GERAN-SystemInformation.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HandoverFromUTRANCommand_GSM_v690ext_IEs__geran_SystemInfoType_PR {
	HandoverFromUTRANCommand_GSM_v690ext_IEs__geran_SystemInfoType_PR_NOTHING,	/* No components present */
	HandoverFromUTRANCommand_GSM_v690ext_IEs__geran_SystemInfoType_PR_sI,
	HandoverFromUTRANCommand_GSM_v690ext_IEs__geran_SystemInfoType_PR_pSI
} HandoverFromUTRANCommand_GSM_v690ext_IEs__geran_SystemInfoType_PR;

/* HandoverFromUTRANCommand-GSM-v690ext-IEs */
typedef struct HandoverFromUTRANCommand_GSM_v690ext_IEs {
	struct HandoverFromUTRANCommand_GSM_v690ext_IEs__geran_SystemInfoType {
		HandoverFromUTRANCommand_GSM_v690ext_IEs__geran_SystemInfoType_PR present;
		union HandoverFromUTRANCommand_GSM_v690ext_IEs__geran_SystemInfoType_u {
			GERAN_SystemInformation_t	 sI;
			GERAN_SystemInformation_t	 pSI;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *geran_SystemInfoType;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HandoverFromUTRANCommand_GSM_v690ext_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HandoverFromUTRANCommand_GSM_v690ext_IEs;

#ifdef __cplusplus
}
#endif

#endif	/* _HandoverFromUTRANCommand_GSM_v690ext_IEs_H_ */
#include <asn_internal.h>
