/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_HS_DSCH_DrxCycleFach_H_
#define	_HS_DSCH_DrxCycleFach_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HS_DSCH_DrxCycleFach {
	HS_DSCH_DrxCycleFach_f4	= 0,
	HS_DSCH_DrxCycleFach_f8	= 1,
	HS_DSCH_DrxCycleFach_f16	= 2,
	HS_DSCH_DrxCycleFach_f32	= 3
} e_HS_DSCH_DrxCycleFach;

/* HS-DSCH-DrxCycleFach */
typedef long	 HS_DSCH_DrxCycleFach_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HS_DSCH_DrxCycleFach;
asn_struct_free_f HS_DSCH_DrxCycleFach_free;
asn_struct_print_f HS_DSCH_DrxCycleFach_print;
asn_constr_check_f HS_DSCH_DrxCycleFach_constraint;
ber_type_decoder_f HS_DSCH_DrxCycleFach_decode_ber;
der_type_encoder_f HS_DSCH_DrxCycleFach_encode_der;
xer_type_decoder_f HS_DSCH_DrxCycleFach_decode_xer;
xer_type_encoder_f HS_DSCH_DrxCycleFach_encode_xer;
per_type_decoder_f HS_DSCH_DrxCycleFach_decode_uper;
per_type_encoder_f HS_DSCH_DrxCycleFach_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _HS_DSCH_DrxCycleFach_H_ */
#include <asn_internal.h>
