/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "../asn/PDU-definitions.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_InterRATHandoverInfo_r3_add_ext_IEs_H_
#define	_InterRATHandoverInfo_r3_add_ext_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InterRATHandoverInfo-v690ext1-IEs.h"
#include "InterRATHandoverInfo-v7e0ext-IEs.h"
#include "InterRATHandoverInfo-v7f0ext-IEs.h"
#include "InterRATHandoverInfoBand-va40ext-IEs.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InterRATHandoverInfo-r3-add-ext-IEs */
typedef struct InterRATHandoverInfo_r3_add_ext_IEs {
	InterRATHandoverInfo_v690ext1_IEs_t	 interRATHandoverInfo_v690ext1;
	struct InterRATHandoverInfo_r3_add_ext_IEs__v7e0NonCriticalExtensions {
		InterRATHandoverInfo_v7e0ext_IEs_t	 interRATHandoverInfo_v7e0ext;
		struct InterRATHandoverInfo_r3_add_ext_IEs__v7e0NonCriticalExtensions__v7f0NonCriticalExtensions {
			InterRATHandoverInfo_v7f0ext_IEs_t	 interRATHandoverInfo_v7f0ext;
			struct InterRATHandoverInfo_r3_add_ext_IEs__v7e0NonCriticalExtensions__v7f0NonCriticalExtensions__va40NonCriticalExtensions {
				InterRATHandoverInfoBand_va40ext_IEs_t	 interRATHandoverInfo_va40ext;
				struct InterRATHandoverInfo_r3_add_ext_IEs__v7e0NonCriticalExtensions__v7f0NonCriticalExtensions__va40NonCriticalExtensions__nonCriticalExtensions {
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *nonCriticalExtensions;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *va40NonCriticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *v7f0NonCriticalExtensions;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *v7e0NonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterRATHandoverInfo_r3_add_ext_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterRATHandoverInfo_r3_add_ext_IEs;

#ifdef __cplusplus
}
#endif

#endif	/* _InterRATHandoverInfo_r3_add_ext_IEs_H_ */
#include <asn_internal.h>
