/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_IntraFrequencyMeasurement_r4_H_
#define	_IntraFrequencyMeasurement_r4_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct IntraFreqCellInfoList_r4;
struct IntraFreqMeasQuantity;
struct IntraFreqReportingQuantity;
struct MeasurementValidity;
struct IntraFreqReportCriteria_r4;

/* IntraFrequencyMeasurement-r4 */
typedef struct IntraFrequencyMeasurement_r4 {
	struct IntraFreqCellInfoList_r4	*intraFreqCellInfoList	/* OPTIONAL */;
	struct IntraFreqMeasQuantity	*intraFreqMeasQuantity	/* OPTIONAL */;
	struct IntraFreqReportingQuantity	*intraFreqReportingQuantity	/* OPTIONAL */;
	struct MeasurementValidity	*measurementValidity	/* OPTIONAL */;
	struct IntraFreqReportCriteria_r4	*reportCriteria	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntraFrequencyMeasurement_r4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntraFrequencyMeasurement_r4;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "IntraFreqCellInfoList-r4.h"
#include "IntraFreqMeasQuantity.h"
#include "IntraFreqReportingQuantity.h"
#include "MeasurementValidity.h"
#include "IntraFreqReportCriteria-r4.h"

#endif	/* _IntraFrequencyMeasurement_r4_H_ */
#include <asn_internal.h>
