/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_IP_Spacing_H_
#define	_IP_Spacing_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IP_Spacing {
	IP_Spacing_e5	= 0,
	IP_Spacing_e7	= 1,
	IP_Spacing_e10	= 2,
	IP_Spacing_e15	= 3,
	IP_Spacing_e20	= 4,
	IP_Spacing_e30	= 5,
	IP_Spacing_e40	= 6,
	IP_Spacing_e50	= 7
} e_IP_Spacing;

/* IP-Spacing */
typedef long	 IP_Spacing_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IP_Spacing;
asn_struct_free_f IP_Spacing_free;
asn_struct_print_f IP_Spacing_print;
asn_constr_check_f IP_Spacing_constraint;
ber_type_decoder_f IP_Spacing_decode_ber;
der_type_encoder_f IP_Spacing_encode_der;
xer_type_decoder_f IP_Spacing_decode_xer;
xer_type_encoder_f IP_Spacing_encode_xer;
per_type_decoder_f IP_Spacing_decode_uper;
per_type_encoder_f IP_Spacing_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _IP_Spacing_H_ */
#include <asn_internal.h>
