/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_MAC_InactivityThreshold_H_
#define	_MAC_InactivityThreshold_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MAC_InactivityThreshold {
	MAC_InactivityThreshold_e_dch_tti_1	= 0,
	MAC_InactivityThreshold_e_dch_tti_2	= 1,
	MAC_InactivityThreshold_e_dch_tti_4	= 2,
	MAC_InactivityThreshold_e_dch_tti_8	= 3,
	MAC_InactivityThreshold_e_dch_tti_16	= 4,
	MAC_InactivityThreshold_e_dch_tti_32	= 5,
	MAC_InactivityThreshold_e_dch_tti_64	= 6,
	MAC_InactivityThreshold_e_dch_tti_128	= 7,
	MAC_InactivityThreshold_e_dch_tti_256	= 8,
	MAC_InactivityThreshold_e_dch_tti_512	= 9,
	MAC_InactivityThreshold_e_dch_tti_Infinity	= 10,
	MAC_InactivityThreshold_spare5	= 11,
	MAC_InactivityThreshold_spare4	= 12,
	MAC_InactivityThreshold_spare3	= 13,
	MAC_InactivityThreshold_spare2	= 14,
	MAC_InactivityThreshold_spare1	= 15
} e_MAC_InactivityThreshold;

/* MAC-InactivityThreshold */
typedef long	 MAC_InactivityThreshold_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MAC_InactivityThreshold;
asn_struct_free_f MAC_InactivityThreshold_free;
asn_struct_print_f MAC_InactivityThreshold_print;
asn_constr_check_f MAC_InactivityThreshold_constraint;
ber_type_decoder_f MAC_InactivityThreshold_decode_ber;
der_type_encoder_f MAC_InactivityThreshold_encode_der;
xer_type_decoder_f MAC_InactivityThreshold_decode_xer;
xer_type_encoder_f MAC_InactivityThreshold_encode_xer;
per_type_decoder_f MAC_InactivityThreshold_decode_uper;
per_type_encoder_f MAC_InactivityThreshold_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MAC_InactivityThreshold_H_ */
#include <asn_internal.h>
