/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_MAC_ehs_AddReconfReordQ_TDD128_v9c0ext_H_
#define	_MAC_ehs_AddReconfReordQ_TDD128_v9c0ext_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MAC-ehs-WindowSize-TDD128-v9c0ext.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MAC-ehs-AddReconfReordQ-TDD128-v9c0ext */
typedef struct MAC_ehs_AddReconfReordQ_TDD128_v9c0ext {
	MAC_ehs_WindowSize_TDD128_v9c0ext_t	*mac_ehsWindowSize_extension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MAC_ehs_AddReconfReordQ_TDD128_v9c0ext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MAC_ehs_AddReconfReordQ_TDD128_v9c0ext;

#ifdef __cplusplus
}
#endif

#endif	/* _MAC_ehs_AddReconfReordQ_TDD128_v9c0ext_H_ */
#include <asn_internal.h>
