/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_MaxPhysChPerTimeslot_H_
#define	_MaxPhysChPerTimeslot_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MaxPhysChPerTimeslot {
	MaxPhysChPerTimeslot_ts1	= 0,
	MaxPhysChPerTimeslot_ts2	= 1
} e_MaxPhysChPerTimeslot;

/* MaxPhysChPerTimeslot */
typedef long	 MaxPhysChPerTimeslot_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MaxPhysChPerTimeslot;
asn_struct_free_f MaxPhysChPerTimeslot_free;
asn_struct_print_f MaxPhysChPerTimeslot_print;
asn_constr_check_f MaxPhysChPerTimeslot_constraint;
ber_type_decoder_f MaxPhysChPerTimeslot_decode_ber;
der_type_encoder_f MaxPhysChPerTimeslot_encode_der;
xer_type_decoder_f MaxPhysChPerTimeslot_decode_xer;
xer_type_encoder_f MaxPhysChPerTimeslot_encode_xer;
per_type_decoder_f MaxPhysChPerTimeslot_decode_uper;
per_type_encoder_f MaxPhysChPerTimeslot_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MaxPhysChPerTimeslot_H_ */
#include <asn_internal.h>
