/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_MBMS_RequiredUEAction_UMod_H_
#define	_MBMS_RequiredUEAction_UMod_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MBMS_RequiredUEAction_UMod {
	MBMS_RequiredUEAction_UMod_none	= 0,
	MBMS_RequiredUEAction_UMod_acquirePTM_RBInfo	= 1,
	MBMS_RequiredUEAction_UMod_requestPTPRB	= 2
} e_MBMS_RequiredUEAction_UMod;

/* MBMS-RequiredUEAction-UMod */
typedef long	 MBMS_RequiredUEAction_UMod_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBMS_RequiredUEAction_UMod;
asn_struct_free_f MBMS_RequiredUEAction_UMod_free;
asn_struct_print_f MBMS_RequiredUEAction_UMod_print;
asn_constr_check_f MBMS_RequiredUEAction_UMod_constraint;
ber_type_decoder_f MBMS_RequiredUEAction_UMod_decode_ber;
der_type_encoder_f MBMS_RequiredUEAction_UMod_encode_der;
xer_type_decoder_f MBMS_RequiredUEAction_UMod_decode_xer;
xer_type_encoder_f MBMS_RequiredUEAction_UMod_encode_xer;
per_type_decoder_f MBMS_RequiredUEAction_UMod_decode_uper;
per_type_encoder_f MBMS_RequiredUEAction_UMod_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MBMS_RequiredUEAction_UMod_H_ */
#include <asn_internal.h>
