/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Internode-definitions"
 * 	found in "../asn/Internode-definitions.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_MeasurementCapability_r4_H_
#define	_MeasurementCapability_r4_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CompressedModeMeasCapability-r4.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MeasurementCapability-r4 */
typedef struct MeasurementCapability_r4 {
	CompressedModeMeasCapability_r4_t	 downlinkCompressedMode;
	CompressedModeMeasCapability_r4_t	 uplinkCompressedMode;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasurementCapability_r4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasurementCapability_r4;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasurementCapability_r4_H_ */
#include <asn_internal.h>
