/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_MeasurementIdentity_H_
#define	_MeasurementIdentity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MeasurementIdentity */
typedef long	 MeasurementIdentity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasurementIdentity;
asn_struct_free_f MeasurementIdentity_free;
asn_struct_print_f MeasurementIdentity_print;
asn_constr_check_f MeasurementIdentity_constraint;
ber_type_decoder_f MeasurementIdentity_decode_ber;
der_type_encoder_f MeasurementIdentity_encode_der;
xer_type_decoder_f MeasurementIdentity_decode_xer;
xer_type_encoder_f MeasurementIdentity_encode_xer;
per_type_decoder_f MeasurementIdentity_decode_uper;
per_type_encoder_f MeasurementIdentity_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasurementIdentity_H_ */
#include <asn_internal.h>
