/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_MultiflowConfigurationInfo_H_
#define	_MultiflowConfigurationInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MultiflowCellType.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MultiflowConfigurationInfo__timeReferenceCell {
	MultiflowConfigurationInfo__timeReferenceCell_true	= 0
} e_MultiflowConfigurationInfo__timeReferenceCell;

/* MultiflowConfigurationInfo */
typedef struct MultiflowConfigurationInfo {
	MultiflowCellType_t	 cellType;
	long	*timeReferenceCell	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MultiflowConfigurationInfo_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_timeReferenceCell_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MultiflowConfigurationInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _MultiflowConfigurationInfo_H_ */
#include <asn_internal.h>
