/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "../asn/PDU-definitions.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_PhysicalChannelReconfiguration_H_
#define	_PhysicalChannelReconfiguration_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PhysicalChannelReconfiguration-r3-IEs.h"
#include "PhysicalChannelReconfiguration-v3a0ext.h"
#include <BIT_STRING.h>
#include "PhysicalChannelReconfiguration-v4b0ext-IEs.h"
#include "PhysicalChannelReconfiguration-v590ext-IEs.h"
#include "PhysicalChannelReconfiguration-v690ext-IEs.h"
#include "PhysicalChannelReconfiguration-v770ext-IEs.h"
#include <constr_SEQUENCE.h>
#include "RRC-TransactionIdentifier.h"
#include "PhysicalChannelReconfiguration-r4-IEs.h"
#include "PhysicalChannelReconfiguration-r5-IEs.h"
#include "PhysicalChannelReconfiguration-r6-IEs.h"
#include "PhysicalChannelReconfiguration-v6b0ext-IEs.h"
#include "PhysicalChannelReconfiguration-r7-IEs.h"
#include "PhysicalChannelReconfiguration-v780ext-IEs.h"
#include "PhysicalChannelReconfiguration-v7d0ext-IEs.h"
#include "PhysicalChannelReconfiguration-v7f0ext-IEs.h"
#include "PhysicalChannelReconfiguration-v7g0ext-IEs.h"
#include "PhysicalChannelReconfiguration-r8-IEs.h"
#include "PhysicalChannelReconfiguration-v890ext-IEs.h"
#include "PhysicalChannelReconfiguration-v8a0ext-IEs.h"
#include "PhysicalChannelReconfiguration-r9-IEs.h"
#include "PhysicalChannelReconfiguration-v950ext-IEs.h"
#include "PhysicalChannelReconfiguration-r10-IEs.h"
#include "PhysicalChannelReconfiguration-vb50ext-IEs.h"
#include "PhysicalChannelReconfiguration-r11-IEs.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PhysicalChannelReconfiguration_PR {
	PhysicalChannelReconfiguration_PR_NOTHING,	/* No components present */
	PhysicalChannelReconfiguration_PR_r3,
	PhysicalChannelReconfiguration_PR_later_than_r3
} PhysicalChannelReconfiguration_PR;
typedef enum PhysicalChannelReconfiguration__later_than_r3__criticalExtensions_PR {
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions_PR_NOTHING,	/* No components present */
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions_PR_r4,
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions_PR_criticalExtensions
} PhysicalChannelReconfiguration__later_than_r3__criticalExtensions_PR;
typedef enum PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions_PR {
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions_PR_NOTHING,	/* No components present */
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions_PR_r5,
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions_PR_criticalExtensions
} PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions_PR;
typedef enum PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions_PR {
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions_PR_NOTHING,	/* No components present */
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions_PR_r6,
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions_PR_criticalExtensions
} PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions_PR;
typedef enum PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR {
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR_NOTHING,	/* No components present */
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR_r7,
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR_criticalExtensions
} PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR;
typedef enum PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR {
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR_NOTHING,	/* No components present */
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR_r8,
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR_criticalExtensions
} PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR;
typedef enum PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR {
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR_NOTHING,	/* No components present */
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR_r9,
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR_criticalExtensions
} PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR;
typedef enum PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR {
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR_NOTHING,	/* No components present */
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR_r10,
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR_criticalExtensions
} PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR;
typedef enum PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR {
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR_NOTHING,	/* No components present */
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR_r11,
	PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR_criticalExtensions
} PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR;

/* PhysicalChannelReconfiguration */
typedef struct PhysicalChannelReconfiguration {
	PhysicalChannelReconfiguration_PR present;
	union PhysicalChannelReconfiguration_u {
		struct PhysicalChannelReconfiguration__r3 {
			PhysicalChannelReconfiguration_r3_IEs_t	 physicalChannelReconfiguration_r3;
			struct PhysicalChannelReconfiguration__r3__v3a0NonCriticalExtensions {
				PhysicalChannelReconfiguration_v3a0ext_t	 physicalChannelReconfiguration_v3a0ext;
				struct PhysicalChannelReconfiguration__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions {
					BIT_STRING_t	*physicalChannelReconfiguration_r3_add_ext	/* OPTIONAL */;
					struct PhysicalChannelReconfiguration__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v4b0NonCriticalExtenstions {
						PhysicalChannelReconfiguration_v4b0ext_IEs_t	 physicalChannelReconfiguration_v4b0ext;
						struct PhysicalChannelReconfiguration__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v4b0NonCriticalExtenstions__v590NonCriticalExtenstions {
							PhysicalChannelReconfiguration_v590ext_IEs_t	 physicalChannelReconfiguration_v590ext;
							struct PhysicalChannelReconfiguration__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v4b0NonCriticalExtenstions__v590NonCriticalExtenstions__v690NonCriticalExtensions {
								PhysicalChannelReconfiguration_v690ext_IEs_t	 physicalChannelReconfiguration_v690ext;
								struct PhysicalChannelReconfiguration__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v4b0NonCriticalExtenstions__v590NonCriticalExtenstions__v690NonCriticalExtensions__v770NonCriticalExtensions {
									PhysicalChannelReconfiguration_v770ext_IEs_t	 physicalChannelReconfiguration_v770ext;
									struct PhysicalChannelReconfiguration__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v4b0NonCriticalExtenstions__v590NonCriticalExtenstions__v690NonCriticalExtensions__v770NonCriticalExtensions__nonCriticalExtensions {
										
										/* Context for parsing across buffer boundaries */
										asn_struct_ctx_t _asn_ctx;
									} *nonCriticalExtensions;
									
									/* Context for parsing across buffer boundaries */
									asn_struct_ctx_t _asn_ctx;
								} *v770NonCriticalExtensions;
								
								/* Context for parsing across buffer boundaries */
								asn_struct_ctx_t _asn_ctx;
							} *v690NonCriticalExtensions;
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} *v590NonCriticalExtenstions;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} *v4b0NonCriticalExtenstions;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *laterNonCriticalExtensions;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *v3a0NonCriticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} r3;
		struct PhysicalChannelReconfiguration__later_than_r3 {
			RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
			struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions {
				PhysicalChannelReconfiguration__later_than_r3__criticalExtensions_PR present;
				union PhysicalChannelReconfiguration__later_than_r3__criticalExtensions_u {
					struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__r4 {
						PhysicalChannelReconfiguration_r4_IEs_t	 physicalChannelReconfiguration_r4;
						struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__r4__v4d0NonCriticalExtensions {
							BIT_STRING_t	*physicalChannelReconfiguration_r4_add_ext	/* OPTIONAL */;
							struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__r4__v4d0NonCriticalExtensions__v590NonCriticalExtenstions {
								PhysicalChannelReconfiguration_v590ext_IEs_t	 physicalChannelReconfiguration_v590ext;
								struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__r4__v4d0NonCriticalExtensions__v590NonCriticalExtenstions__v690NonCriticalExtensions {
									PhysicalChannelReconfiguration_v690ext_IEs_t	 physicalChannelReconfiguration_v690ext;
									struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__r4__v4d0NonCriticalExtensions__v590NonCriticalExtenstions__v690NonCriticalExtensions__v770NonCriticalExtensions {
										PhysicalChannelReconfiguration_v770ext_IEs_t	 physicalChannelReconfiguration_v770ext;
										struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__r4__v4d0NonCriticalExtensions__v590NonCriticalExtenstions__v690NonCriticalExtensions__v770NonCriticalExtensions__nonCriticalExtensions {
											
											/* Context for parsing across buffer boundaries */
											asn_struct_ctx_t _asn_ctx;
										} *nonCriticalExtensions;
										
										/* Context for parsing across buffer boundaries */
										asn_struct_ctx_t _asn_ctx;
									} *v770NonCriticalExtensions;
									
									/* Context for parsing across buffer boundaries */
									asn_struct_ctx_t _asn_ctx;
								} *v690NonCriticalExtensions;
								
								/* Context for parsing across buffer boundaries */
								asn_struct_ctx_t _asn_ctx;
							} *v590NonCriticalExtenstions;
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} *v4d0NonCriticalExtensions;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} r4;
					struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions {
						PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions_PR present;
						union PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions_u {
							struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__r5 {
								PhysicalChannelReconfiguration_r5_IEs_t	 physicalChannelReconfiguration_r5;
								BIT_STRING_t	*physicalChannelReconfiguration_r5_add_ext	/* OPTIONAL */;
								struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__r5__v690NonCriticalExtensions {
									PhysicalChannelReconfiguration_v690ext_IEs_t	 physicalChannelReconfiguration_v690ext;
									struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__r5__v690NonCriticalExtensions__v770NonCriticalExtensions {
										PhysicalChannelReconfiguration_v770ext_IEs_t	 physicalChannelReconfiguration_v770ext;
										struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__r5__v690NonCriticalExtensions__v770NonCriticalExtensions__nonCriticalExtensions {
											
											/* Context for parsing across buffer boundaries */
											asn_struct_ctx_t _asn_ctx;
										} *nonCriticalExtensions;
										
										/* Context for parsing across buffer boundaries */
										asn_struct_ctx_t _asn_ctx;
									} *v770NonCriticalExtensions;
									
									/* Context for parsing across buffer boundaries */
									asn_struct_ctx_t _asn_ctx;
								} *v690NonCriticalExtensions;
								
								/* Context for parsing across buffer boundaries */
								asn_struct_ctx_t _asn_ctx;
							} r5;
							struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions {
								PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions_PR present;
								union PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions_u {
									struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__r6 {
										PhysicalChannelReconfiguration_r6_IEs_t	 physicalChannelReconfiguration_r6;
										BIT_STRING_t	*physicalChannelReconfiguration_r6_add_ext	/* OPTIONAL */;
										struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__r6__v6b0NonCriticalExtensions {
											PhysicalChannelReconfiguration_v6b0ext_IEs_t	 physicalChannelReconfiguration_v6b0ext;
											struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__r6__v6b0NonCriticalExtensions__v770NonCriticalExtensions {
												PhysicalChannelReconfiguration_v770ext_IEs_t	 physicalChannelReconfiguration_v770ext;
												struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__r6__v6b0NonCriticalExtensions__v770NonCriticalExtensions__nonCriticalExtensions {
													
													/* Context for parsing across buffer boundaries */
													asn_struct_ctx_t _asn_ctx;
												} *nonCriticalExtensions;
												
												/* Context for parsing across buffer boundaries */
												asn_struct_ctx_t _asn_ctx;
											} *v770NonCriticalExtensions;
											
											/* Context for parsing across buffer boundaries */
											asn_struct_ctx_t _asn_ctx;
										} *v6b0NonCriticalExtensions;
										
										/* Context for parsing across buffer boundaries */
										asn_struct_ctx_t _asn_ctx;
									} r6;
									struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions {
										PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR present;
										union PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_u {
											struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r7 {
												PhysicalChannelReconfiguration_r7_IEs_t	 physicalChannelReconfiguration_r7;
												BIT_STRING_t	*physicalChannelReconfiguration_r7_add_ext	/* OPTIONAL */;
												struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r7__v780NonCriticalExtensions {
													PhysicalChannelReconfiguration_v780ext_IEs_t	 physicalChannelReconfiguration_v780ext;
													struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r7__v780NonCriticalExtensions__v7d0NonCriticalExtensions {
														PhysicalChannelReconfiguration_v7d0ext_IEs_t	 physicalChannelReconfiguration_v7d0ext;
														struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r7__v780NonCriticalExtensions__v7d0NonCriticalExtensions__v7f0NonCriticalExtensions {
															PhysicalChannelReconfiguration_v7f0ext_IEs_t	 physicalChannelReconfiguration_v7f0ext;
															struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r7__v780NonCriticalExtensions__v7d0NonCriticalExtensions__v7f0NonCriticalExtensions__v7g0NonCriticalExtensions {
																PhysicalChannelReconfiguration_v7g0ext_IEs_t	 physicalChannelReconfiguration_v7g0ext;
																struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r7__v780NonCriticalExtensions__v7d0NonCriticalExtensions__v7f0NonCriticalExtensions__v7g0NonCriticalExtensions__nonCriticalExtensions {
																	
																	/* Context for parsing across buffer boundaries */
																	asn_struct_ctx_t _asn_ctx;
																} *nonCriticalExtensions;
																
																/* Context for parsing across buffer boundaries */
																asn_struct_ctx_t _asn_ctx;
															} *v7g0NonCriticalExtensions;
															
															/* Context for parsing across buffer boundaries */
															asn_struct_ctx_t _asn_ctx;
														} *v7f0NonCriticalExtensions;
														
														/* Context for parsing across buffer boundaries */
														asn_struct_ctx_t _asn_ctx;
													} *v7d0NonCriticalExtensions;
													
													/* Context for parsing across buffer boundaries */
													asn_struct_ctx_t _asn_ctx;
												} *v780NonCriticalExtensions;
												
												/* Context for parsing across buffer boundaries */
												asn_struct_ctx_t _asn_ctx;
											} r7;
											struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions {
												PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR present;
												union PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_u {
													struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r8 {
														PhysicalChannelReconfiguration_r8_IEs_t	 physicalChannelReconfiguration_r8;
														BIT_STRING_t	*physicalChannelReconfiguration_r8_add_ext	/* OPTIONAL */;
														struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r8__v7d0NonCriticalExtensions {
															PhysicalChannelReconfiguration_v7d0ext_IEs_t	 physicalChannelReconfiguration_v7d0ext;
															struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r8__v7d0NonCriticalExtensions__v7f0NonCriticalExtensions {
																PhysicalChannelReconfiguration_v7f0ext_IEs_t	 physicalChannelReconfiguration_v7f0ext;
																struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r8__v7d0NonCriticalExtensions__v7f0NonCriticalExtensions__v890NonCriticalExtensions {
																	PhysicalChannelReconfiguration_v890ext_IEs_t	 physicalChannelReconfiguration_v890ext;
																	struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r8__v7d0NonCriticalExtensions__v7f0NonCriticalExtensions__v890NonCriticalExtensions__v7g0NonCriticalExtensions {
																		PhysicalChannelReconfiguration_v7g0ext_IEs_t	 physicalChannelReconfiguration_v7g0ext;
																		struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r8__v7d0NonCriticalExtensions__v7f0NonCriticalExtensions__v890NonCriticalExtensions__v7g0NonCriticalExtensions__v8a0NonCriticalExtensions {
																			PhysicalChannelReconfiguration_v8a0ext_IEs_t	 physicalChannelReconfiguration_v8a0ext;
																			struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r8__v7d0NonCriticalExtensions__v7f0NonCriticalExtensions__v890NonCriticalExtensions__v7g0NonCriticalExtensions__v8a0NonCriticalExtensions__nonCriticalExtensions {
																				
																				/* Context for parsing across buffer boundaries */
																				asn_struct_ctx_t _asn_ctx;
																			} *nonCriticalExtensions;
																			
																			/* Context for parsing across buffer boundaries */
																			asn_struct_ctx_t _asn_ctx;
																		} *v8a0NonCriticalExtensions;
																		
																		/* Context for parsing across buffer boundaries */
																		asn_struct_ctx_t _asn_ctx;
																	} *v7g0NonCriticalExtensions;
																	
																	/* Context for parsing across buffer boundaries */
																	asn_struct_ctx_t _asn_ctx;
																} *v890NonCriticalExtensions;
																
																/* Context for parsing across buffer boundaries */
																asn_struct_ctx_t _asn_ctx;
															} *v7f0NonCriticalExtensions;
															
															/* Context for parsing across buffer boundaries */
															asn_struct_ctx_t _asn_ctx;
														} *v7d0NonCriticalExtensions;
														
														/* Context for parsing across buffer boundaries */
														asn_struct_ctx_t _asn_ctx;
													} r8;
													struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions {
														PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR present;
														union PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_u {
															struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r9 {
																PhysicalChannelReconfiguration_r9_IEs_t	 physicalChannelReconfiguration_r9;
																BIT_STRING_t	*physicalChannelReconfiguration_r9_add_ext	/* OPTIONAL */;
																struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r9__v950NonCriticalExtensions {
																	PhysicalChannelReconfiguration_v950ext_IEs_t	 physicalChannelReconfiguration_v950ext;
																	struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r9__v950NonCriticalExtensions__nonCriticalExtensions {
																		
																		/* Context for parsing across buffer boundaries */
																		asn_struct_ctx_t _asn_ctx;
																	} *nonCriticalExtensions;
																	
																	/* Context for parsing across buffer boundaries */
																	asn_struct_ctx_t _asn_ctx;
																} *v950NonCriticalExtensions;
																
																/* Context for parsing across buffer boundaries */
																asn_struct_ctx_t _asn_ctx;
															} r9;
															struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions {
																PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR present;
																union PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_u {
																	struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r10 {
																		PhysicalChannelReconfiguration_r10_IEs_t	 physicalChannelReconfiguration_r10;
																		BIT_STRING_t	*physicalChannelReconfiguration_r10_add_ext	/* OPTIONAL */;
																		struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r10__vb50NonCriticalExtensions {
																			PhysicalChannelReconfiguration_vb50ext_IEs_t	 physicalChannelReconfiguration_vb50ext;
																			struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r10__vb50NonCriticalExtensions__nonCriticalExtensions {
																				
																				/* Context for parsing across buffer boundaries */
																				asn_struct_ctx_t _asn_ctx;
																			} *nonCriticalExtensions;
																			
																			/* Context for parsing across buffer boundaries */
																			asn_struct_ctx_t _asn_ctx;
																		} *vb50NonCriticalExtensions;
																		
																		/* Context for parsing across buffer boundaries */
																		asn_struct_ctx_t _asn_ctx;
																	} r10;
																	struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions {
																		PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR present;
																		union PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_u {
																			struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r11 {
																				PhysicalChannelReconfiguration_r11_IEs_t	 physicalChannelReconfiguration_r11;
																				BIT_STRING_t	*physicalChannelReconfiguration_r11_add_ext	/* OPTIONAL */;
																				struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r11__nonCriticalExtensions {
																					
																					/* Context for parsing across buffer boundaries */
																					asn_struct_ctx_t _asn_ctx;
																				} *nonCriticalExtensions;
																				
																				/* Context for parsing across buffer boundaries */
																				asn_struct_ctx_t _asn_ctx;
																			} r11;
																			struct PhysicalChannelReconfiguration__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions {
																				
																				/* Context for parsing across buffer boundaries */
																				asn_struct_ctx_t _asn_ctx;
																			} criticalExtensions;
																		} choice;
																		
																		/* Context for parsing across buffer boundaries */
																		asn_struct_ctx_t _asn_ctx;
																	} criticalExtensions;
																} choice;
																
																/* Context for parsing across buffer boundaries */
																asn_struct_ctx_t _asn_ctx;
															} criticalExtensions;
														} choice;
														
														/* Context for parsing across buffer boundaries */
														asn_struct_ctx_t _asn_ctx;
													} criticalExtensions;
												} choice;
												
												/* Context for parsing across buffer boundaries */
												asn_struct_ctx_t _asn_ctx;
											} criticalExtensions;
										} choice;
										
										/* Context for parsing across buffer boundaries */
										asn_struct_ctx_t _asn_ctx;
									} criticalExtensions;
								} choice;
								
								/* Context for parsing across buffer boundaries */
								asn_struct_ctx_t _asn_ctx;
							} criticalExtensions;
						} choice;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} criticalExtensions;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} criticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} later_than_r3;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PhysicalChannelReconfiguration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PhysicalChannelReconfiguration;

#ifdef __cplusplus
}
#endif

#endif	/* _PhysicalChannelReconfiguration_H_ */
#include <asn_internal.h>
