/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_PichChannelisationCodeList_LCR_r4_H_
#define	_PichChannelisationCodeList_LCR_r4_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DL-TS-ChannelisationCode.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PichChannelisationCodeList-LCR-r4 */
typedef struct PichChannelisationCodeList_LCR_r4 {
	A_SEQUENCE_OF(DL_TS_ChannelisationCode_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PichChannelisationCodeList_LCR_r4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PichChannelisationCodeList_LCR_r4;

#ifdef __cplusplus
}
#endif

#endif	/* _PichChannelisationCodeList_LCR_r4_H_ */
#include <asn_internal.h>
