/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_PowerOffsetPilot_pdpdch_H_
#define	_PowerOffsetPilot_pdpdch_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PowerOffsetPilot-pdpdch */
typedef long	 PowerOffsetPilot_pdpdch_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PowerOffsetPilot_pdpdch;
asn_struct_free_f PowerOffsetPilot_pdpdch_free;
asn_struct_print_f PowerOffsetPilot_pdpdch_print;
asn_constr_check_f PowerOffsetPilot_pdpdch_constraint;
ber_type_decoder_f PowerOffsetPilot_pdpdch_decode_ber;
der_type_encoder_f PowerOffsetPilot_pdpdch_encode_der;
xer_type_decoder_f PowerOffsetPilot_pdpdch_decode_xer;
xer_type_encoder_f PowerOffsetPilot_pdpdch_encode_xer;
per_type_decoder_f PowerOffsetPilot_pdpdch_decode_uper;
per_type_encoder_f PowerOffsetPilot_pdpdch_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PowerOffsetPilot_pdpdch_H_ */
#include <asn_internal.h>
