/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_PUSCH_SysInfo_LCR_r4_H_
#define	_PUSCH_SysInfo_LCR_r4_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PUSCH-Identity.h"
#include "PUSCH-Info-LCR-r4.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TransportFormatSet;
struct TFCS;

/* PUSCH-SysInfo-LCR-r4 */
typedef struct PUSCH_SysInfo_LCR_r4 {
	PUSCH_Identity_t	 pusch_Identity;
	PUSCH_Info_LCR_r4_t	 pusch_Info;
	struct TransportFormatSet	*usch_TFS	/* OPTIONAL */;
	struct TFCS	*usch_TFCS	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PUSCH_SysInfo_LCR_r4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PUSCH_SysInfo_LCR_r4;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TransportFormatSet.h"
#include "TFCS.h"

#endif	/* _PUSCH_SysInfo_LCR_r4_H_ */
#include <asn_internal.h>
