/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_RB_MappingOption_H_
#define	_RB_MappingOption_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UL_LogicalChannelMappings;
struct DL_LogicalChannelMappingList;

/* RB-MappingOption */
typedef struct RB_MappingOption {
	struct UL_LogicalChannelMappings	*ul_LogicalChannelMappings	/* OPTIONAL */;
	struct DL_LogicalChannelMappingList	*dl_LogicalChannelMappingList	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RB_MappingOption_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RB_MappingOption;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "UL-LogicalChannelMappings.h"
#include "DL-LogicalChannelMappingList.h"

#endif	/* _RB_MappingOption_H_ */
#include <asn_internal.h>
