/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Internode-definitions"
 * 	found in "../asn/Internode-definitions.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_RFC3095_Context_List_H_
#define	_RFC3095_Context_List_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DL_RFC3095_Context;
struct UL_RFC3095_Context;

/* RFC3095-Context-List */
typedef struct RFC3095_Context_List {
	A_SEQUENCE_OF(struct RFC3095_Context_List__Member {
		struct DL_RFC3095_Context	*dl_RFC3095_Context	/* OPTIONAL */;
		struct UL_RFC3095_Context	*ul_RFC3095_Context	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RFC3095_Context_List_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RFC3095_Context_List;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DL-RFC3095-Context.h"
#include "UL-RFC3095-Context.h"

#endif	/* _RFC3095_Context_List_H_ */
#include <asn_internal.h>
