/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_SCCPCH_SystemInformationList_LCR_r4_ext_H_
#define	_SCCPCH_SystemInformationList_LCR_r4_ext_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SCCPCH_SystemInformation_LCR_r4_ext;

/* SCCPCH-SystemInformationList-LCR-r4-ext */
typedef struct SCCPCH_SystemInformationList_LCR_r4_ext {
	A_SEQUENCE_OF(struct SCCPCH_SystemInformation_LCR_r4_ext) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SCCPCH_SystemInformationList_LCR_r4_ext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SCCPCH_SystemInformationList_LCR_r4_ext;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SCCPCH-SystemInformation-LCR-r4-ext.h"

#endif	/* _SCCPCH_SystemInformationList_LCR_r4_ext_H_ */
#include <asn_internal.h>
