/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_SIBOccurrenceIdentityAndValueTag_H_
#define	_SIBOccurrenceIdentityAndValueTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SIBOccurIdentity.h"
#include "SIBOccurValueTag.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SIBOccurrenceIdentityAndValueTag */
typedef struct SIBOccurrenceIdentityAndValueTag {
	SIBOccurIdentity_t	 sibOccurIdentity;
	SIBOccurValueTag_t	 sibOccurValueTag;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SIBOccurrenceIdentityAndValueTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SIBOccurrenceIdentityAndValueTag;

#ifdef __cplusplus
}
#endif

#endif	/* _SIBOccurrenceIdentityAndValueTag_H_ */
#include <asn_internal.h>
