/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_SRB_delay_H_
#define	_SRB_delay_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SRB-delay */
typedef long	 SRB_delay_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SRB_delay;
asn_struct_free_f SRB_delay_free;
asn_struct_print_f SRB_delay_print;
asn_constr_check_f SRB_delay_constraint;
ber_type_decoder_f SRB_delay_decode_ber;
der_type_encoder_f SRB_delay_encode_der;
xer_type_decoder_f SRB_delay_decode_xer;
xer_type_encoder_f SRB_delay_encode_xer;
per_type_decoder_f SRB_delay_decode_uper;
per_type_encoder_f SRB_delay_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SRB_delay_H_ */
#include <asn_internal.h>
