/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_SysInfoType19_H_
#define	_SysInfoType19_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UTRA-PriorityInfoList.h"
#include "SysInfoType19-v920ext.h"
#include "SysInfoType19-va80ext.h"
#include "SysInfoType19-vb30ext.h"
#include "SysInfoType19-vb50ext.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GSM_PriorityInfoList;
struct EUTRA_FrequencyAndPriorityInfoList;

/* SysInfoType19 */
typedef struct SysInfoType19 {
	UTRA_PriorityInfoList_t	 utra_PriorityInfoList;
	struct GSM_PriorityInfoList	*gsm_PriorityInfoList	/* OPTIONAL */;
	struct EUTRA_FrequencyAndPriorityInfoList	*eutra_FrequencyAndPriorityInfoList	/* OPTIONAL */;
	struct SysInfoType19__v920NonCriticalExtensions {
		SysInfoType19_v920ext_t	 sysInfoType19_v920ext;
		struct SysInfoType19__v920NonCriticalExtensions__va80NonCriticalExtensions {
			SysInfoType19_va80ext_t	 sysInfoType19_va80ext;
			struct SysInfoType19__v920NonCriticalExtensions__va80NonCriticalExtensions__vb30NonCriticalExtensions {
				SysInfoType19_vb30ext_t	 sysInfoType19_vb30ext;
				struct SysInfoType19__v920NonCriticalExtensions__va80NonCriticalExtensions__vb30NonCriticalExtensions__vb50NonCriticalExtensions {
					SysInfoType19_vb50ext_t	 sysInfoType19_vb50ext;
					struct SysInfoType19__v920NonCriticalExtensions__va80NonCriticalExtensions__vb30NonCriticalExtensions__vb50NonCriticalExtensions__nonCriticalExtensions {
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} *nonCriticalExtensions;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *vb50NonCriticalExtensions;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *vb30NonCriticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *va80NonCriticalExtensions;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *v920NonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SysInfoType19_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SysInfoType19;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GSM-PriorityInfoList.h"
#include "EUTRA-FrequencyAndPriorityInfoList.h"

#endif	/* _SysInfoType19_H_ */
#include <asn_internal.h>
