/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_SysInfoType15_2ter_H_
#define	_SysInfoType15_2ter_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UE-Positioning-GANSS-AddNavigationModels.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SysInfoType15-2ter */
typedef struct SysInfoType15_2ter {
	UE_Positioning_GANSS_AddNavigationModels_t	 ue_positioning_GANSS_AddNavigationModels;
	struct SysInfoType15_2ter__nonCriticalExtensions {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SysInfoType15_2ter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SysInfoType15_2ter;

#ifdef __cplusplus
}
#endif

#endif	/* _SysInfoType15_2ter_H_ */
#include <asn_internal.h>
