/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_TreselectionScalingFactor2_H_
#define	_TreselectionScalingFactor2_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TreselectionScalingFactor2 */
typedef long	 TreselectionScalingFactor2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TreselectionScalingFactor2;
asn_struct_free_f TreselectionScalingFactor2_free;
asn_struct_print_f TreselectionScalingFactor2_print;
asn_constr_check_f TreselectionScalingFactor2_constraint;
ber_type_decoder_f TreselectionScalingFactor2_decode_ber;
der_type_encoder_f TreselectionScalingFactor2_encode_der;
xer_type_decoder_f TreselectionScalingFactor2_decode_xer;
xer_type_encoder_f TreselectionScalingFactor2_encode_xer;
per_type_decoder_f TreselectionScalingFactor2_decode_uper;
per_type_encoder_f TreselectionScalingFactor2_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TreselectionScalingFactor2_H_ */
#include <asn_internal.h>
