/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_UE_Positioning_MeasuredResults_H_
#define	_UE_Positioning_MeasuredResults_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UE_Positioning_OTDOA_Measurement;
struct UE_Positioning_PositionEstimateInfo;
struct UE_Positioning_GPS_MeasurementResults;
struct UE_Positioning_Error;

/* UE-Positioning-MeasuredResults */
typedef struct UE_Positioning_MeasuredResults {
	struct UE_Positioning_OTDOA_Measurement	*ue_positioning_OTDOA_Measurement	/* OPTIONAL */;
	struct UE_Positioning_PositionEstimateInfo	*ue_positioning_PositionEstimateInfo	/* OPTIONAL */;
	struct UE_Positioning_GPS_MeasurementResults	*ue_positioning_GPS_Measurement	/* OPTIONAL */;
	struct UE_Positioning_Error	*ue_positioning_Error	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_Positioning_MeasuredResults_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_Positioning_MeasuredResults;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "UE-Positioning-OTDOA-Measurement.h"
#include "UE-Positioning-PositionEstimateInfo.h"
#include "UE-Positioning-GPS-MeasurementResults.h"
#include "UE-Positioning-Error.h"

#endif	/* _UE_Positioning_MeasuredResults_H_ */
#include <asn_internal.h>
