/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "../asn/PDU-definitions.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_UEInformationRequest_r11_IEs_H_
#define	_UEInformationRequest_r11_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UEInformationRequest_r11_IEs__loggedMeasReportRequest {
	UEInformationRequest_r11_IEs__loggedMeasReportRequest_true	= 0
} e_UEInformationRequest_r11_IEs__loggedMeasReportRequest;
typedef enum UEInformationRequest_r11_IEs__loggedANRReportRequest {
	UEInformationRequest_r11_IEs__loggedANRReportRequest_true	= 0
} e_UEInformationRequest_r11_IEs__loggedANRReportRequest;
typedef enum UEInformationRequest_r11_IEs__connectionEstablishmentFailureRequest {
	UEInformationRequest_r11_IEs__connectionEstablishmentFailureRequest_true	= 0
} e_UEInformationRequest_r11_IEs__connectionEstablishmentFailureRequest;

/* UEInformationRequest-r11-IEs */
typedef struct UEInformationRequest_r11_IEs {
	long	*loggedMeasReportRequest	/* OPTIONAL */;
	long	*loggedANRReportRequest	/* OPTIONAL */;
	long	*connectionEstablishmentFailureRequest	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEInformationRequest_r11_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_loggedMeasReportRequest_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_loggedANRReportRequest_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_connectionEstablishmentFailureRequest_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_UEInformationRequest_r11_IEs;

#ifdef __cplusplus
}
#endif

#endif	/* _UEInformationRequest_r11_IEs_H_ */
#include <asn_internal.h>
