/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_UESpecificBehaviourInformation1interRAT_H_
#define	_UESpecificBehaviourInformation1interRAT_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UESpecificBehaviourInformation1interRAT */
typedef BIT_STRING_t	 UESpecificBehaviourInformation1interRAT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UESpecificBehaviourInformation1interRAT;
asn_struct_free_f UESpecificBehaviourInformation1interRAT_free;
asn_struct_print_f UESpecificBehaviourInformation1interRAT_print;
asn_constr_check_f UESpecificBehaviourInformation1interRAT_constraint;
ber_type_decoder_f UESpecificBehaviourInformation1interRAT_decode_ber;
der_type_encoder_f UESpecificBehaviourInformation1interRAT_encode_der;
xer_type_decoder_f UESpecificBehaviourInformation1interRAT_decode_xer;
xer_type_encoder_f UESpecificBehaviourInformation1interRAT_encode_xer;
per_type_decoder_f UESpecificBehaviourInformation1interRAT_decode_uper;
per_type_encoder_f UESpecificBehaviourInformation1interRAT_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UESpecificBehaviourInformation1interRAT_H_ */
#include <asn_internal.h>
