/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_UL_AddReconfTransChInformation_r6_H_
#define	_UL_AddReconfTransChInformation_r6_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UL-TrCH-Type.h"
#include "TransportChannelIdentity.h"
#include "TransportFormatSet.h"
#include <constr_SEQUENCE.h>
#include "E-DCH-TTI.h"
#include <NativeEnumerated.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UL_AddReconfTransChInformation_r6_PR {
	UL_AddReconfTransChInformation_r6_PR_NOTHING,	/* No components present */
	UL_AddReconfTransChInformation_r6_PR_dch_usch,
	UL_AddReconfTransChInformation_r6_PR_e_dch
} UL_AddReconfTransChInformation_r6_PR;
typedef enum UL_AddReconfTransChInformation_r6__e_dch__harq_Info {
	UL_AddReconfTransChInformation_r6__e_dch__harq_Info_rv0	= 0,
	UL_AddReconfTransChInformation_r6__e_dch__harq_Info_rvtable	= 1
} e_UL_AddReconfTransChInformation_r6__e_dch__harq_Info;

/* Forward declarations */
struct E_DCH_AddReconf_MAC_d_FlowList;

/* UL-AddReconfTransChInformation-r6 */
typedef struct UL_AddReconfTransChInformation_r6 {
	UL_AddReconfTransChInformation_r6_PR present;
	union UL_AddReconfTransChInformation_r6_u {
		struct UL_AddReconfTransChInformation_r6__dch_usch {
			UL_TrCH_Type_t	 ul_TransportChannelType;
			TransportChannelIdentity_t	 transportChannelIdentity;
			TransportFormatSet_t	 transportFormatSet;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} dch_usch;
		struct UL_AddReconfTransChInformation_r6__e_dch {
			E_DCH_TTI_t	 tti;
			long	 harq_Info;
			struct E_DCH_AddReconf_MAC_d_FlowList	*addReconf_MAC_d_FlowList	/* OPTIONAL */;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} e_dch;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UL_AddReconfTransChInformation_r6_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_harq_Info_8;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_UL_AddReconfTransChInformation_r6;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "E-DCH-AddReconf-MAC-d-FlowList.h"

#endif	/* _UL_AddReconfTransChInformation_r6_H_ */
#include <asn_internal.h>
