/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../asn/InformationElements.asn"
 * 	`asn1c -fcompound-names -fnative-types`
 */

#ifndef	_UTRAN_GPSReferenceTimeResult_H_
#define	_UTRAN_GPSReferenceTimeResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#include "PrimaryCPICH-Info.h"
#include "CellParametersID.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UTRAN_GPSReferenceTimeResult__modeSpecificInfo_PR {
	UTRAN_GPSReferenceTimeResult__modeSpecificInfo_PR_NOTHING,	/* No components present */
	UTRAN_GPSReferenceTimeResult__modeSpecificInfo_PR_fdd,
	UTRAN_GPSReferenceTimeResult__modeSpecificInfo_PR_tdd
} UTRAN_GPSReferenceTimeResult__modeSpecificInfo_PR;

/* UTRAN-GPSReferenceTimeResult */
typedef struct UTRAN_GPSReferenceTimeResult {
	struct UTRAN_GPSReferenceTimeResult__ue_GPSTimingOfCell {
		long	 ms_part;
		unsigned long	 ls_part;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ue_GPSTimingOfCell;
	struct UTRAN_GPSReferenceTimeResult__modeSpecificInfo {
		UTRAN_GPSReferenceTimeResult__modeSpecificInfo_PR present;
		union UTRAN_GPSReferenceTimeResult__modeSpecificInfo_u {
			struct UTRAN_GPSReferenceTimeResult__modeSpecificInfo__fdd {
				PrimaryCPICH_Info_t	 referenceIdentity;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} fdd;
			struct UTRAN_GPSReferenceTimeResult__modeSpecificInfo__tdd {
				CellParametersID_t	 referenceIdentity;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} tdd;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} modeSpecificInfo;
	long	 sfn;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UTRAN_GPSReferenceTimeResult_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ls_part_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_UTRAN_GPSReferenceTimeResult;

#ifdef __cplusplus
}
#endif

#endif	/* _UTRAN_GPSReferenceTimeResult_H_ */
#include <asn_internal.h>
