--  Remove all auto-generated views and tables
DROP VIEW IF EXISTS a1;
DROP VIEW IF EXISTS a2;
DROP VIEW IF EXISTS a4;
DROP VIEW IF EXISTS k1;
DROP VIEW IF EXISTS k2;
DROP VIEW IF EXISTS t1;
DROP VIEW IF EXISTS r1;
DROP VIEW IF EXISTS r2;
DROP VIEW IF EXISTS c1;
DROP VIEW IF EXISTS c2;
DROP VIEW IF EXISTS c3;
DROP VIEW IF EXISTS c4;
DROP VIEW IF EXISTS t3;
DROP VIEW IF EXISTS t4;

DROP TABLE IF EXISTS si;
DROP VIEW IF EXISTS ci;
DROP VIEW IF EXISTS timestamps;
DROP TABLE IF EXISTS config;
DROP TABLE IF EXISTS catcher;

DROP VIEW IF EXISTS dup_arfcns;
DROP VIEW IF EXISTS max_cipher;
DROP VIEW IF EXISTS cells_with_neig_arfcn;
DROP VIEW IF EXISTS cells_with_neig_cell;
DROP VIEW IF EXISTS cells_neig_count;
DROP VIEW IF EXISTS cells_ref_by_neig_cell;
DROP VIEW IF EXISTS cells_ref_by_neig_count;
